
var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da=Object.assign({},f),ea="./this.program",k="",fa;"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);_scriptName&&(k=_scriptName);k.startsWith("blob:")?k="":k=k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1);fa=a=>fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var ha=f.print||console.log.bind(console),ia=f.printErr||console.error.bind(console);
Object.assign(f,da);da=null;f.thisProgram&&(ea=f.thisProgram);var ja=f.wasmBinary,ma,na=!1,oa,n,q,pa,qa,r,t,v,x;function ra(){var a=ma.buffer;f.HEAP8=n=new Int8Array(a);f.HEAP16=pa=new Int16Array(a);f.HEAPU8=q=new Uint8Array(a);f.HEAPU16=qa=new Uint16Array(a);f.HEAP32=r=new Int32Array(a);f.HEAPU32=t=new Uint32Array(a);f.HEAPF32=v=new Float32Array(a);f.HEAPF64=x=new Float64Array(a)}var sa=[],ta=[],ua=[];function va(){var a=f.preRun.shift();sa.unshift(a)}var wa=0,xa=null,ya=null;
function za(a){f.onAbort?.(a);a="Aborted("+a+")";ia(a);na=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Aa=a=>a.startsWith("data:application/octet-stream;base64,"),Ba;function Ca(a){if(a==Ba&&ja)return new Uint8Array(ja);throw"both async and sync fetching of the wasm failed";}function Da(a){return ja?Promise.resolve().then(()=>Ca(a)):fa(a).then(b=>new Uint8Array(b),()=>Ca(a))}
function Ea(a,b,c){return Da(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{ia(`failed to asynchronously prepare wasm: ${d}`);za(d)})}function Fa(a,b){var c=Ba;return ja||"function"!=typeof WebAssembly.instantiateStreaming||Aa(c)||"function"!=typeof fetch?Ea(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){ia(`wasm streaming compile failed: ${e}`);ia("falling back to ArrayBuffer instantiation");return Ea(c,a,b)}))}
var Ga={3109316:()=>window.innerWidth,3109346:()=>window.innerHeight,3109377:(a,b,c)=>{f.SDL2||(f.SDL2={});var d=f.SDL2;d.ui!==f.canvas&&(d.Eh=f.createContext(f.canvas,!1,!0),d.ui=f.canvas);if(d.w!==a||d.h!==b||d.Hi!==d.Eh)d.image=d.Eh.createImageData(a,b),d.w=a,d.h=b,d.Hi=d.Eh;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var g=r[b];a[e]=g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.yi!==a&&(d.xi=new Int32Array(a.buffer),
d.zi=new Uint8Array(a.buffer),d.yi=a),a=d.xi,c=a.length,a.set(r.subarray(b,b+c)),a=d.zi,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Eh.putImageData(d.image,0,0)},3110845:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var h=g.getContext("2d");a=h.createImageData(a,b);b=a.data;e/=4;var l=0,m;if("undefined"!==typeof CanvasPixelArray&&
b instanceof CanvasPixelArray)for(m=b.length;l<m;){var p=r[e];b[l]=p&255;b[l+1]=p>>8&255;b[l+2]=p>>16&255;b[l+3]=p>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),m=b.length,b.set(r.subarray(e,e+m));h.putImageData(a,0,0);c=0===c&&0===d?"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=y(c.length+1);z(c,d,c.length+1);return d},3111833:a=>{f.canvas&&(f.canvas.style.cursor=a?A(q,a):"")},3111916:()=>{f.canvas&&(f.canvas.style.cursor="none")}};
class Ia{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ja=a=>{for(;0<a.length;)a.shift()(f)},Ka=f.noExitRuntime||!0,La=[],Ma,B=a=>{var b=La[a];b||(a>=La.length&&(La.length=a+1),La[a]=b=Ma.get(a));return b},Na="undefined"!=typeof TextDecoder?new TextDecoder:void 0,A=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Na)return Na.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|
h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Oa=(a,b)=>a?A(q,a,b):"",Pa,C=a=>{for(var b="";q[a];)b+=Pa[q[a++]];return b},Qa={},Ra={},Sa={},E,Ta=a=>{throw new E(a);},Ua,Va=(a,b)=>{function c(l){l=b(l);if(l.length!==d.length)throw new Ua("Mismatched type converter count");for(var m=0;m<d.length;++m)F(d[m],l[m])}var d=[];d.forEach(l=>Sa[l]=a);var e=Array(a.length),g=[],h=0;a.forEach((l,m)=>{Ra.hasOwnProperty(l)?
e[m]=Ra[l]:(g.push(l),Qa.hasOwnProperty(l)||(Qa[l]=[]),Qa[l].push(()=>{e[m]=Ra[l];++h;h===g.length&&c(e)}))});0===g.length&&c(e)};function Wa(a,b,c={}){var d=b.name;if(!a)throw new E(`type "${d}" must have a positive integer typeid pointer`);if(Ra.hasOwnProperty(a)){if(c.Gi)return;throw new E(`Cannot register type '${d}' twice`);}Ra[a]=b;delete Sa[a];Qa.hasOwnProperty(a)&&(b=Qa[a],delete Qa[a],b.forEach(e=>e()))}function F(a,b,c={}){return Wa(a,b,c)}
var Xa=[],Ya=[],Za=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Xa.pop()||Ya.length;Ya[b]=a;Ya[b+1]=1;return b}};function $a(a){return this.fromWireType(t[a>>2])}
var ab={name:"emscripten::val",fromWireType:a=>{if(!a)throw new E("Cannot use deleted val. handle = "+a);var b=Ya[a];9<a&&0===--Ya[a+1]&&(Ya[a]=void 0,Xa.push(a));return b},toWireType:(a,b)=>Za(b),Kh:8,readValueFromPointer:$a,Gh:null},db=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(v[c>>2])};case 8:return function(c){return this.fromWireType(x[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},eb=(a,b)=>Object.defineProperty(b,"name",{value:a}),fb=a=>
{for(;a.length;){var b=a.pop();a.pop()(b)}};function gb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].Gh)return!0;return!1}function hb(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=eb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
var ib=(a,b)=>{if(void 0===f[a].Dh){var c=f[a];f[a]=function(...d){if(!f[a].Dh.hasOwnProperty(d.length))throw new E(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${f[a].Dh})!`);return f[a].Dh[d.length].apply(this,d)};f[a].Dh=[];f[a].Dh[c.ji]=c}},jb=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].Dh&&void 0!==f[a].Dh[c])throw new E(`Cannot register public name '${a}' twice`);ib(a,a);if(f[a].Dh.hasOwnProperty(c))throw new E(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
f[a].Dh[c]=b}else f[a]=b,f[a].ji=c},kb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(t[b+4*d>>2]);return c},lb=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,f["dynCall_"+a])(b,...c)):b=B(b)(...c);return b},mb=(a,b)=>(...c)=>lb(a,b,c),nb=(a,b)=>{a=C(a);var c=a.includes("j")?mb(a,b):B(b);if("function"!=typeof c)throw new E(`unknown function pointer with signature ${a}: ${b}`);return c},ob,qb=a=>{a=pb(a);var b=C(a);G(a);return b},rb=(a,b)=>{function c(g){e[g]||Ra[g]||(Sa[g]?Sa[g].forEach(c):(d.push(g),
e[g]=!0))}var d=[],e={};b.forEach(c);throw new ob(`${a}: `+d.map(qb).join([", "]));},sb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},tb=(a,b,c)=>{switch(b){case 1:return c?d=>n[d]:d=>q[d];case 2:return c?d=>pa[d>>1]:d=>qa[d>>1];case 4:return c?d=>r[d>>2]:d=>t[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},z=(a,b,c)=>{var d=q;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);
h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(b>=c)break;d[b++]=h}else{if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6}else{if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63}d[b++]=128|h>>6&63}d[b++]=128|h&63}}d[b]=0;return b-e},ub=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},vb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,wb=(a,b)=>{var c=a>>1;for(var d=
c+b/2;!(c>=d)&&qa[c];)++c;c<<=1;if(32<c-a&&vb)return vb.decode(q.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=pa[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},xb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)pa[b>>1]=a.charCodeAt(e),b+=2;pa[b>>1]=0;return b-d},yb=a=>2*a.length,zb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=r[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},
Ab=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);g=65536+((g&1023)<<10)|h&1023}r[b>>2]=g;b+=4;if(b+4>c)break}r[b>>2]=0;return b-d},Bb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Cb=0,Db={},Eb=a=>{if(!(a instanceof Ia||"unwind"==a))throw a;},Fb=a=>{oa=a;Ka||0<Cb||(f.onExit?.(a),na=!0);throw new Ia(a);},Gb=()=>{if(!(Ka||0<Cb))try{var a=oa;oa=
a;Fb(a)}catch(b){Eb(b)}},Hb=a=>{if(!na)try{a(),Gb()}catch(b){Eb(b)}},Ib=!1,Jb=!1,Kb=[];
function Lb(){function a(){Jb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!Mb){Mb=!0;var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!Jb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Nb=!1,Ob=void 0,Pb=void 0;
function Qb(){if(!Ib)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Rb=[];function Sb(){var a=f.canvas;Rb.forEach(b=>b(a.width,a.height))}
function Tb(a,b,c){b&&c?(a.Ni=b,a.Fi=c):(b=a.Ni,c=a.Fi);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}Pb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Mb,H=12288,Ub=!1,Vb=0,Wb=0,Xb=0,I={alpha:!1,depth:!1,stencil:!1,antialias:!1},Yb={},Zb,J,$b=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},ac=1,bc=[],K=[],cc=[],dc=[],ec=[],M=[],fc=[],N=[],O=[],Q=[],gc=[],hc=[],ic={},jc={},kc=4,lc=0,mc=a=>{for(var b=ac++,c=a.length;c<b;c++)a[c]=null;return b},nc=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=J[c](),h=g&&mc(d);g?(g.name=h,d[h]=g):R||=1282;r[b+4*e>>2]=h}},pc=(a,b)=>{a.Uh||(a.Uh=a.getContext,a.getContext=function(d,e){e=a.Uh(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?
oc(c,b):0},oc=(a,b)=>{var c=mc(N),d={handle:c,attributes:b,version:b.oi,Hh:a};a.canvas&&(a.canvas.Lh=d);N[c]=d;("undefined"==typeof b.Bi||b.Bi)&&qc(d);return c},rc=a=>{S=N[a];f.Eh=J=S?.Hh},qc=a=>{a||=S;if(!a.Ii){a.Ii=!0;var b=a.Hh;b.cj=b.getExtension("WEBGL_multi_draw");b.Di=b.getExtension("EXT_polygon_offset_clamp");b.Ci=b.getExtension("EXT_clip_control");b.Mi=b.getExtension("WEBGL_polygon_mode");b.Wi=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.aj=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Ah=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Ah)b.Ah=b.getExtension("EXT_disjoint_timer_query");$b(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},sc={},R,S,T=a=>{var b=ub(a)+1,c=y(b);c&&z(a,c,b);return c},Jc=(a,b,c,d,e)=>{function g(){return h<tc?(Gb(),!1):!0}uc=a;vc=d;var h=tc;wc=!1;xc=function(){if(!na)if(0<yc.length){var l=yc.shift();l.Yi(l.Qi);if(zc){var m=zc,p=0==m%1?m-1:Math.floor(m);zc=l.Ti?p:(8*m+(p+.5))/9}f.setStatus&&
(l=f.statusMessage||"Please wait...",m=zc??0,p=Ac.Xi??0,m?m<p?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));g()&&setTimeout(xc,0)}else if(g())if(Bc=Bc+1|0,1==Cc&&1<Dc&&0!=Bc%Dc)Ec();else{0==Cc&&(Fc=performance.now());a:if(!na){for(l of Gc)if(!1===l())break a;Hb(a);for(m of Hc)m()}g()&&Ec()}};e||(b&&0<b?Ic(0,1E3/b):Ic(1,1),Ec());if(c)throw"unwind";},wc=!1,Ec=null,tc=0,uc=null,vc=0,Cc=0,Dc=0,Bc=0,yc=[],Gc=[],Hc=[];function Kc(){Ec=null;tc++}var Lc=0;
function Mc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Lc)Lc=b+1E3/60;else for(;b+2>=Lc;)Lc+=1E3/60;setTimeout(a,Math.max(Lc-b,0))}}
var Ac={},xc,zc,Fc,Nc,Ic=(a,b)=>{Cc=a;Dc=b;if(uc)if(wc||=!0,0==a)Ec=function(){setTimeout(xc,Math.max(0,Fc+b-performance.now())|0)};else if(1==a)Ec=function(){Mc(xc)};else if(2==a){if("undefined"==typeof Nc)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Nc=d=>{c.push(d);postMessage("setimmediate","*")}}else Nc=setImmediate;Ec=function(){Nc(xc)}}},Oc=[],Pc=(a,b)=>{Oc.length=
0;for(var c;c=q[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Oc.push(112==c?t[b>>2]:105==c?r[b>>2]:x[b>>3]);b+=d?8:4}return Oc};function Qc(a){var b=V.Bh[a];b.target.removeEventListener(b.xh,b.mi,b.yh);V.Bh.splice(a,1)}function Rc(a,b,c){function d(g,h){if(g.length!=h.length)return!1;for(var l in g)if(g[l]!=h[l])return!1;return!0}for(var e of V.Ih)if(e.di==a&&d(e.ki,c))return;V.Ih.push({di:a,ri:b,ki:c});V.Ih.sort((g,h)=>g.ri<h.ri)}function Sc(a){V.Ih=V.Ih.filter(b=>b.di!=a)}
function Tc(){return navigator.userActivation?navigator.userActivation.isActive:V.$h&&V.vi.Nh}function Uc(){if(Tc()){var a=V.Ih;V.Ih=[];for(var b of a)b.di(...b.ki)}}function W(a){if(!a.target)return-4;if(a.zh)a.mi=function(c){++V.$h;V.vi=a;Uc();a.Ch(c);Uc();--V.$h},a.target.addEventListener(a.xh,a.mi,a.yh),V.Bh.push(a);else for(var b=0;b<V.Bh.length;++b)V.Bh[b].target==a.target&&V.Bh[b].xh==a.xh&&Qc(b--);return 0}
function Vc(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var V={Ri:0,Zh:0,ai:0,Th:0,ii:0,fi:0,Xh:0,Vi:0,dj:0,Ui:0,Yh:0,bi:0,hi:0,ei:0,ej(){for(;V.Bh.length;)Qc(V.Bh.length-1);V.Ih=[]},$h:0,Ih:[],Bh:[],Ki:(a,b)=>{for(var c=0;c<V.Bh.length;++c)V.Bh[c].target!=a||b&&b!=V.Bh[c].xh||Qc(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Wc={},Xc=[0,document,window],X=a=>{a=2<a?a?A(q,a):"":a;return Xc[a]||document.querySelector(a)},Yc=(a,b,c)=>{a=X(a);if(!a)return-4;r[b>>2]=a.width;r[c>>2]=a.height},$c=a=>{var b=ub(a)+
1,c=Zc(b);z(a,c,b);return c},cd=a=>{var b=ad(),c=Zc(8),d=c+4;a=$c(a.id);Yc(a,c,d);c=[r[c>>2],r[d>>2]];bd(b);return c},dd=(a,b,c)=>{a=X(a);if(!a)return-4;a.width=b;a.height=c;return 0},ed=(a,b,c)=>{if(a.Si){var d=ad();a=$c(a.id);dd(a,b,c);bd(d)}else a.width=b,a.height=c},fd=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),ed(a,d,e),a.style.width=g,a.style.height=
h,a.style.backgroundColor=l,m||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=m,a.style.paddingLeft=p,a.style.paddingRight=u,a.style.paddingTop=D,a.style.paddingBottom=w,a.style.marginLeft=U,a.style.marginRight=ka,a.style.marginTop=bb,a.style.marginBottom=P,document.body.style.margin=L,document.documentElement.style.overflow=la,document.body.scroll=cb,a.style.Jh=Ha,a.Lh&&a.Lh.Hh.viewport(0,0,d,e),Wc.Oh&&B(Wc.Oh)(37,0,Wc.li))}var c=cd(a),d=c[0],e=c[1],g=a.style.width,
h=a.style.height,l=a.style.backgroundColor,m=document.body.style.backgroundColor,p=a.style.paddingLeft,u=a.style.paddingRight,D=a.style.paddingTop,w=a.style.paddingBottom,U=a.style.marginLeft,ka=a.style.marginRight,bb=a.style.marginTop,P=a.style.marginBottom,L=document.body.style.margin,la=document.documentElement.style.overflow,cb=document.body.scroll,Ha=a.style.Jh;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},gd=(a,b,c)=>{a.style.paddingLeft=
a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},hd=a=>0>Xc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},jd=(a,b)=>{if(0!=b.ci||0!=b.Vh){fd(a);var c=b.Li?innerWidth:screen.width,d=b.Li?innerHeight:screen.height,e=hd(a),g=e.width;e=e.height;var h=cd(a),l=h[0];h=h[1];3==b.ci?(gd(a,(d-e)/2,(c-g)/2),c=g,d=e):2==b.ci&&(c*h<l*d?(g=h*c/l,gd(a,(d-g)/2,0),d=g):(g=l*d/h,gd(a,0,(c-g)/2),c=g));var m;(m=a.style).backgroundColor||(m.backgroundColor="black");let p;(p=document.body.style).backgroundColor||
(p.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Ei&&(a.style.Jh="optimizeSpeed",a.style.Jh="-moz-crisp-edges",a.style.Jh="-o-crisp-edges",a.style.Jh="-webkit-optimize-contrast",a.style.Jh="optimize-contrast",a.style.Jh="crisp-edges",a.style.Jh="pixelated");m=2==b.Vh?devicePixelRatio:1;0!=b.Vh&&(c=c*m|0,d=d*m|0,ed(a,c,d),a.Lh&&a.Lh.Hh.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return V.fullscreenEnabled()?-3:-1;Wc=b;b.Oh&&B(b.Oh)(37,0,b.li);return 0},kd=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},ld=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)n[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
n[a+1104]=b.connected;r[a+1108>>2]=b.index;r[a+8>>2]=b.axes.length;r[a+12>>2]=b.buttons.length;z(b.id,a+1112,64);z(b.mapping,a+1176,64)},md=a=>J.activeTexture(a),nd=(a,b)=>{J.attachShader(K[a],M[b])},od=(a,b)=>{35051==a?J.Wh=b:35052==a&&(J.Fh=b);J.bindBuffer(a,bc[b])},pd=(a,b,c)=>{J.bindBufferBase(a,b,bc[c])},qd=(a,b,c,d,e)=>{J.bindBufferRange(a,b,bc[c],d,e)},rd=(a,b)=>{J.bindFramebuffer(a,cc[b])},sd=(a,b)=>{J.bindTexture(a,ec[b])},td=a=>{J.bindVertexArray(fc[a])},ud=a=>J.blendEquation(a),vd=(a,b)=>
J.blendEquationSeparate(a,b),wd=(a,b,c,d)=>J.blendFuncSeparate(a,b,c,d),xd=(a,b,c,d)=>{c&&b?J.bufferData(a,q,d,c,b):J.bufferData(a,b,d)},yd=(a,b,c,d)=>{c&&J.bufferSubData(a,b,q,d,c)},zd=a=>J.checkFramebufferStatus(a),Ad=a=>J.clear(a),Bd=(a,b,c)=>{J.clearBufferfv(a,b,v,c>>2)},Cd=(a,b,c)=>{J.clearBufferuiv(a,b,t,c>>2)},Dd=(a,b,c,d)=>J.clearColor(a,b,c,d),Ed=a=>{J.compileShader(M[a])},Fd=()=>{var a=mc(K),b=J.createProgram();b.name=a;b.Sh=b.Qh=b.Rh=0;b.gi=1;K[a]=b;return a},Gd=a=>{var b=mc(M);M[b]=J.createShader(a);
return b},Hd=a=>J.cullFace(a),Id=(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=bc[d];e&&(J.deleteBuffer(e),e.name=0,bc[d]=null,d==J.Wh&&(J.Wh=0),d==J.Fh&&(J.Fh=0))}},Jd=(a,b)=>{for(var c=0;c<a;++c){var d=r[b+4*c>>2],e=cc[d];e&&(J.deleteFramebuffer(e),e.name=0,cc[d]=null)}},Kd=a=>{if(a){var b=K[a];b?(J.deleteProgram(b),b.name=0,K[a]=null):R||=1281}},Ld=a=>{if(a){var b=M[a];b?(J.deleteShader(b),M[a]=null):R||=1281}},Md=(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=ec[d];e&&(J.deleteTexture(e),
e.name=0,ec[d]=null)}},Nd=(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2];J.deleteVertexArray(fc[d]);fc[d]=null}},Od=a=>J.depthFunc(a),Pd=(a,b)=>{J.detachShader(K[a],M[b])},Qd=a=>J.disable(a),Rd=(a,b,c)=>{J.drawArrays(a,b,c)},Sd=(a,b,c,d)=>{J.drawArraysInstanced(a,b,c,d)},Td=[],Ud=(a,b)=>{for(var c=Td[a],d=0;d<a;d++)c[d]=r[b+4*d>>2];J.drawBuffers(c)},Vd=(a,b,c,d)=>{J.drawElements(a,b,c,d)},Wd=(a,b,c,d,e)=>{J.drawElementsInstanced(a,b,c,d,e)},Xd=a=>J.enable(a),Yd=a=>{J.enableVertexAttribArray(a)},Zd=
(a,b,c,d,e)=>{J.framebufferTexture2D(a,b,c,ec[d],e)},$d=(a,b,c,d,e)=>{J.framebufferTextureLayer(a,b,ec[c],d,e)},ae=(a,b)=>{nc(a,b,"createBuffer",bc)},be=(a,b)=>{nc(a,b,"createFramebuffer",cc)},ce=(a,b)=>{nc(a,b,"createTexture",ec)},de=(a,b)=>{nc(a,b,"createVertexArray",fc)},ee=(a,b,c,d,e,g,h,l)=>{b=K[b];if(a=J[a](b,c))d=l&&z(a.name,l,d),e&&(r[e>>2]=d),g&&(r[g>>2]=a.size),h&&(r[h>>2]=a.type)},fe=(a,b)=>J.getAttribLocation(K[a],b?A(q,b):""),ge=(a,b)=>{t[a>>2]=b;t[a+4>>2]=(b-t[a>>2])/4294967296};
function he(){var a=$b(J);return a=a.concat(a.map(b=>"GL_"+b))}
for(var ie=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(R||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=J.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>S.version){R||=1282;return}d=he().length;break;case 33307:case 33308:if(2>S.version){R||=1280;return}d=33307==a?3:0}if(void 0===d)switch(e=J.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=
0;break;default:R||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:r[b+4*a>>2]=e[a];break;case 2:v[b+4*a>>2]=e[a];break;case 4:n[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(g){R||=1280;ia(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${g})`);return}}break;default:R||=1280;ia(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:ge(b,d);break;case 0:r[b>>2]=d;break;case 2:v[b>>2]=d;break;case 4:n[b]=d?1:0}}else R||=1281},je=(a,b,c,d)=>{if(c){b=J.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:R||=1280;return}else if(b instanceof WebGLBuffer)a=b.name|0;else{R||=1280;return}break;default:R||=1280;return}switch(d){case 1:ge(c,a);break;case 0:r[c>>2]=a;break;case 2:v[c>>2]=a;break;
case 4:n[c]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else R||=1281},ke=(a,b)=>ie(a,b,0),le=(a,b,c,d)=>{a=J.getProgramInfoLog(K[a]);null===a&&(a="(unknown error)");b=0<b&&d?z(a,d,b):0;c&&(r[c>>2]=b)},me=(a,b,c)=>{if(c)if(a>=ac)R||=1281;else if(a=K[a],35716==b)a=J.getProgramInfoLog(a),null===a&&(a="(unknown error)"),r[c>>2]=a.length+1;else if(35719==b){if(!a.Sh){var d=J.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Sh=Math.max(a.Sh,J.getActiveUniform(a,
b).name.length+1)}r[c>>2]=a.Sh}else if(35722==b){if(!a.Qh)for(d=J.getProgramParameter(a,35721),b=0;b<d;++b)a.Qh=Math.max(a.Qh,J.getActiveAttrib(a,b).name.length+1);r[c>>2]=a.Qh}else if(35381==b){if(!a.Rh)for(d=J.getProgramParameter(a,35382),b=0;b<d;++b)a.Rh=Math.max(a.Rh,J.getActiveUniformBlockName(a,b).length+1);r[c>>2]=a.Rh}else r[c>>2]=J.getProgramParameter(a,b);else R||=1281},ne=(a,b,c)=>{if(c){a=O[a];b=2>S.version?J.Ah.getQueryObjectEXT(a,b):J.getQueryParameter(a,b);var d;"boolean"==typeof b?
d=b?1:0:d=b;ge(c,d)}else R||=1281},oe=(a,b,c)=>{if(c){a=J.Ah.getQueryObjectEXT(O[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;r[c>>2]=d}else R||=1281},pe=(a,b,c,d)=>{a=J.getShaderInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?z(a,d,b):0;c&&(r[c>>2]=b)},qe=(a,b,c)=>{c?35716==b?(a=J.getShaderInfoLog(M[a]),null===a&&(a="(unknown error)"),r[c>>2]=a?a.length+1:0):35720==b?(a=J.getShaderSource(M[a]),r[c>>2]=a?a.length+1:0):r[c>>2]=J.getShaderParameter(M[a],b):R||=1281},re=(a,b)=>J.getUniformBlockIndex(K[a],
b?A(q,b):""),se=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),te=a=>{var b=a.Mh,c=a.ti,d;if(!b){a.Mh=b={};a.si={};var e=J.getProgramParameter(a,35718);for(d=0;d<e;++d){var g=J.getActiveUniform(a,d);var h=g.name;g=g.size;var l=se(h);l=0<l?h.slice(0,l):h;var m=a.gi;a.gi+=g;c[l]=[g,m];for(h=0;h<g;++h)b[m]=h,a.si[m++]=l}}},ue=(a,b)=>{b=b?A(q,b):"";if(a=K[a]){te(a);var c=a.Mh,d=0,e=b,g=se(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.ti[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||J.getUniformLocation(a,
b)))return d}else R||=1281;return-1},Y=a=>{var b=J.wi;if(b){var c=b.Mh[a];"number"==typeof c&&(b.Mh[a]=c=J.getUniformLocation(b,b.si[a]+(0<c?`[${c}]`:"")));return c}R||=1282},ve=(a,b,c,d)=>{if(c)if(a=K[a],te(a),a=J.getUniform(a,Y(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>2]=a;break;case 2:v[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:v[c+4*b>>2]=a[b]}else R||=1281},we=(a,b,c,d)=>{if(c)if(a=J.getVertexAttrib(a,b),34975==b)r[c>>2]=a&&a.name;
else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>2]=a;break;case 2:v[c>>2]=a;break;case 5:r[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:v[c+4*b>>2]=a[b];break;case 5:r[c+4*b>>2]=Math.fround(a[b])}else R||=1281},ye=(a,b,c)=>{we(a,b,c,0)},ze=a=>J.isEnabled(a),Ae=a=>(a=K[a])?J.isProgram(a):0,Be=a=>(a=fc[a])?J.isVertexArray(a):0,Ce=a=>{a=K[a];J.linkProgram(a);a.Mh=0;a.ti={}},De=a=>J.readBuffer(a),Ee=a=>{a-=5120;return 0==a?n:1==
a?q:2==a?pa:4==a?r:6==a?v:5==a||28922==a||28520==a||30779==a||30782==a?t:qa},Fe=(a,b,c,d,e)=>{a=Ee(a);b=d*((lc||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+kc-1&-kc);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Ge=(a,b,c,d)=>J.scissor(a,b,c,d),He=(a,b,c,d)=>{for(var e="",g=0;g<b;++g)e+=Oa(t[c+4*g>>2],d?t[d+4*g>>2]:void 0);J.shaderSource(M[a],e)},Ie=(a,b,c,d,e,g,h,l,m)=>{if(J.Fh)J.texImage2D(a,
b,c,d,e,g,h,l,m);else if(m){var p=Ee(l);m>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);J.texImage2D(a,b,c,d,e,g,h,l,p,m)}else p=m?Fe(l,h,d,e,m):null,J.texImage2D(a,b,c,d,e,g,h,l,p)},Je=(a,b,c,d,e,g,h,l,m,p)=>{if(J.Fh)J.texImage3D(a,b,c,d,e,g,h,l,m,p);else if(p){var u=Ee(m);J.texImage3D(a,b,c,d,e,g,h,l,m,u,p>>>31-Math.clz32(u.BYTES_PER_ELEMENT))}else J.texImage3D(a,b,c,d,e,g,h,l,m,null)},Ke=(a,b,c)=>J.texParameteri(a,b,c),Le=(a,b)=>{J.uniform1i(Y(a),b)},Me=(a,b,c)=>{a=K[a];J.uniformBlockBinding(a,b,c)},Ne=
(a,b,c,d)=>{b&&J.uniformMatrix4fv(Y(a),!!c,v,d>>2,16*b)},Oe=a=>{a=K[a];J.useProgram(a);J.wi=a},Pe=(a,b)=>{J.vertexAttribDivisor(a,b)},Qe=(a,b,c,d,e)=>{J.vertexAttribIPointer(a,b,c,d,e)},Re=(a,b,c,d,e,g)=>{J.vertexAttribPointer(a,b,c,!!d,e,g)},Se=(a,b,c,d)=>J.viewport(a,b,c,d),Te=(a,b)=>{if(!V.fullscreenEnabled())return-1;a=X(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Tc()?jd(a,b):b.Ai?(Rc(jd,1,[a,b]),1):-2:-3:-4},Ue=()=>{try{if(navigator.getGamepads)return(V.Ph=navigator.getGamepads())?
0:-1}catch(a){navigator.getGamepads=null}return-1},Ve=(a,b)=>{var c={target:X(2),xh:"beforeunload",zh:b,Ch:(d=event)=>{var e=B(b)(28,0,a);e&&=e?A(q,e):"";if(e)return d.preventDefault(),d.returnValue=e},yh:!0};return W(c)},We=(a,b,c,d,e,g)=>{V.Xh||(V.Xh=y(256));a={target:X(a),xh:g,zh:d,Ch:(h=event)=>{var l=h.target.id?h.target.id:"",m=V.Xh;z(Vc(h.target),m+0,128);z(l,m+128,128);B(d)(e,m,b)&&h.preventDefault()},yh:c};return W(a)},Xe=(a,b,c,d,e)=>{V.Yh||(V.Yh=y(276));return W({target:a,xh:e,zh:d,Ch:(g=
event)=>{var h=V.Yh,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,m=!!l;n[h]=m;n[h+1]=V.fullscreenEnabled();var p=m?l:V.Ji,u=p?.id||"";z(Vc(p),h+2,128);z(u,h+130,128);r[h+260>>2]=p?p.clientWidth:0;r[h+264>>2]=p?p.clientHeight:0;r[h+268>>2]=screen.width;r[h+272>>2]=screen.height;m&&(V.Ji=l);B(d)(19,h,b)&&g.preventDefault()},yh:c})},Ye=(a,b,c,d,e)=>{V.Zh||(V.Zh=y(1240));b={target:X(2),Nh:!0,xh:e,zh:c,Ch:(g=event)=>{var h=
V.Zh;ld(h,g.gamepad);B(c)(d,h,a)&&g.preventDefault()},yh:b};return W(b)},Ze=(a,b,c,d,e,g)=>{V.ai||(V.ai=y(160));a={target:X(a),xh:g,zh:d,Ch:h=>{var l=V.ai;x[l>>3]=h.timeStamp;var m=l>>2;r[m+2]=h.location;n[l+12]=h.ctrlKey;n[l+13]=h.shiftKey;n[l+14]=h.altKey;n[l+15]=h.metaKey;n[l+16]=h.repeat;r[m+5]=h.charCode;r[m+6]=h.keyCode;r[m+7]=h.which;z(h.key||"",l+32,32);z(h.code||"",l+64,32);z(h.char||"",l+96,32);z(h.locale||"",l+128,32);B(d)(e,l,b)&&h.preventDefault()},yh:c};return W(a)},$e=(a,b,c)=>{x[a>>
3]=b.timeStamp;var d=a>>2;r[d+2]=b.screenX;r[d+3]=b.screenY;r[d+4]=b.clientX;r[d+5]=b.clientY;n[a+24]=b.ctrlKey;n[a+25]=b.shiftKey;n[a+26]=b.altKey;n[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;r[d+8]=b.movementX;r[d+9]=b.movementY;a=hd(c);r[d+10]=b.clientX-(a.left|0);r[d+11]=b.clientY-(a.top|0)},af=(a,b,c,d,e,g)=>{V.Th||(V.Th=y(64));a=X(a);return W({target:a,Nh:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,xh:g,zh:d,Ch:(h=event)=>{$e(V.Th,h,a);B(d)(e,V.Th,b)&&h.preventDefault()},
yh:c})},bf=(a,b,c,d,e)=>{V.bi||(V.bi=y(257));return W({target:a,xh:e,zh:d,Ch:(g=event)=>{var h=V.bi,l=document.pointerLockElement||document.Uh||document.Pi||document.Oi;n[h]=!!l;var m=l?.id||"";z(Vc(l),h+1,128);z(m,h+129,128);B(d)(20,h,b)&&g.preventDefault()},yh:c})},cf=(a,b,c,d)=>{V.fi||(V.fi=y(36));a=X(a);return W({target:a,xh:"resize",zh:d,Ch:(e=event)=>{if(e.target==a){var g=document.body;if(g){var h=V.fi;r[h>>2]=0;r[h+4>>2]=g.clientWidth;r[h+8>>2]=g.clientHeight;r[h+12>>2]=innerWidth;r[h+16>>
2]=innerHeight;r[h+20>>2]=outerWidth;r[h+24>>2]=outerHeight;r[h+28>>2]=pageXOffset|0;r[h+32>>2]=pageYOffset|0;B(d)(10,h,b)&&e.preventDefault()}}},yh:c})},df=(a,b,c,d,e,g)=>{V.ei||(V.ei=y(1552));a=X(a);return W({target:a,Nh:"touchstart"==g||"touchend"==g,xh:g,zh:d,Ch:h=>{var l={},m=h.touches;for(var p of m)p.ni=p.pi=0,l[p.identifier]=p;for(var u of h.changedTouches)u.ni=1,l[u.identifier]=u;for(var D of h.targetTouches)l[D.identifier].pi=1;m=V.ei;x[m>>3]=h.timeStamp;n[m+12]=h.ctrlKey;n[m+13]=h.shiftKey;
n[m+14]=h.altKey;n[m+15]=h.metaKey;p=m+16;u=hd(a);D=0;for(let w of Object.values(l))if(l=p>>2,r[l]=w.identifier,r[l+1]=w.screenX,r[l+2]=w.screenY,r[l+3]=w.clientX,r[l+4]=w.clientY,r[l+5]=w.pageX,r[l+6]=w.pageY,n[p+28]=w.ni,n[p+29]=w.pi,r[l+8]=w.clientX-(u.left|0),r[l+9]=w.clientY-(u.top|0),p+=48,31<++D)break;r[m+8>>2]=D;B(d)(e,m,b)&&h.preventDefault()},yh:c})},ef=(a,b,c)=>{var d=Xc[1];V.hi||(V.hi=y(8));return W({target:d,xh:"visibilitychange",zh:c,Ch:(e=event)=>{var g=V.hi,h=["hidden","visible","prerender",
"unloaded"].indexOf(document.visibilityState);n[g]=document.hidden;r[g+4>>2]=h;B(c)(21,g,a)&&e.preventDefault()},yh:b})},ff=(a,b,c,d)=>{V.ii||(V.ii=y(96));return W({target:a,Nh:!0,xh:"wheel",zh:d,Ch:(e=event)=>{var g=V.ii;$e(g,e,a);x[g+64>>3]=e.deltaX;x[g+72>>3]=e.deltaY;x[g+80>>3]=e.deltaZ;r[g+88>>2]=e.deltaMode;B(d)(9,g,b)&&e.preventDefault()},yh:c})},gf={},jf=()=>{if(!hf){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&
navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in gf)void 0===gf[b]?delete a[b]:a[b]=gf[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);hf=c}return hf},hf,kf=[null,[],[]],lf=Array(256),mf=0;256>mf;++mf)lf[mf]=String.fromCharCode(mf);Pa=lf;E=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};Ua=f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};Ya.push(0,1,void 0,1,null,1,!0,1,!1,1);
f.count_emval_handles=()=>Ya.length/2-5-Xa.length;ob=f.UnboundTypeError=((a,b)=>{var c=eb(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
f.requestFullscreen=function(a,b){function c(){Ib=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Qb,Ob&&d.requestPointerLock(),Ib=!0,Pb?("undefined"!=typeof SDL&&(r[SDL.screen>>2]=t[SDL.screen>>2]|8388608),Tb(f.canvas),Sb()):Tb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),Pb?("undefined"!=typeof SDL&&(r[SDL.screen>>2]=
t[SDL.screen>>2]&-8388609),Tb(f.canvas),Sb()):Tb(d));f.onFullScreen?.(Ib);f.onFullscreen?.(Ib)}Ob=a;Pb=b;"undefined"==typeof Ob&&(Ob=!0);"undefined"==typeof Pb&&(Pb=!1);var d=f.canvas;Nb||(Nb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};f.setCanvasSize=function(a,b,c){Tb(f.canvas,a,b);c||Sb()};f.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
f.createContext=function(a,b,c,d){if(b&&f.Eh&&a==f.canvas)return f.Eh;var e;if(b){var g={antialias:!1,alpha:!1,oi:2};if(d)for(var h in d)g[h]=d[h];if("undefined"!=typeof sc&&(e=pc(a,g)))var l=N[e].Hh}else l=a.getContext("2d");if(!l)return null;c&&(f.Eh=l,b&&rc(e),Kb.forEach(m=>m()),Lb());return l};f.requestAnimationFrame=Mc;f.pauseMainLoop=Kc;f.resumeMainLoop=function(){tc++;var a=Cc,b=Dc,c=uc;uc=null;Jc(c,0,!1,vc,!0);Ic(a,b);Ec()};f.preMainLoop&&Gc.push(f.preMainLoop);f.postMainLoop&&Hc.push(f.postMainLoop);
for(var nf=0;32>nf;++nf)Td.push(Array(nf));
var pf={Wg:function(a){(a=a?a?A(q,a):"":null)&&window.open(a,"_blank")},gb:(a,b)=>B(a)(b),Da:function(){return 0},ob:()=>{},rb:function(){return 0},mb:()=>{},sb:function(){},nb:()=>{},xb:()=>{za("")},fb:()=>{},Kf:(a,b,c,d)=>{b=C(b);F(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,g){return g?c:d},Kh:8,readValueFromPointer:function(e){return this.fromWireType(q[e])},Gh:null})},db:a=>F(a,ab),ia:(a,b,c)=>{b=C(b);F(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,Kh:8,readValueFromPointer:db(b,
c),Gh:null})},r:(a,b,c,d,e,g,h)=>{var l=kb(b,c);a=C(a);a=sb(a);e=nb(d,e);jb(a,function(){rb(`Cannot call ${a} due to unbound types`,l)},b-1);Va(l,m=>{var p=a;var u=a;m=[m[0],null].concat(m.slice(1));var D=e,w=m.length;if(2>w)throw new E("argTypes array size mismatch! Must at least get return value and 'this' types!");var U=null!==m[1]&&!1,ka=gb(m),bb="void"!==m[0].name;D=[u,Ta,D,g,fb,m[0],m[1]];for(var P=0;P<w-2;++P)D.push(m[P+2]);if(!ka)for(P=U?1:2;P<m.length;++P)null!==m[P].Gh&&D.push(m[P].Gh);
ka=gb(m);P=m.length-2;var L=[],la=["fn"];U&&la.push("thisWired");for(w=0;w<P;++w)L.push(`arg${w}`),la.push(`arg${w}Wired`);L=L.join(",");la=la.join(",");L=`return function (${L}) {\n`;ka&&(L+="var destructors = [];\n");var cb=ka?"destructors":"null",Ha="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");U&&(L+=`var thisWired = classParam['toWireType'](${cb}, this);\n`);for(w=0;w<P;++w)L+=`var arg${w}Wired = argType${w}['toWireType'](${cb}, arg${w});\n`,Ha.push(`argType${w}`);
L+=(bb||h?"var rv = ":"")+`invoker(${la});\n`;if(ka)L+="runDestructors(destructors);\n";else for(w=U?1:2;w<m.length;++w)U=1===w?"thisWired":"arg"+(w-2)+"Wired",null!==m[w].Gh&&(L+=`${U}_dtor(${U});\n`,Ha.push(`${U}_dtor`));bb&&(L+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [xe,rf]=[Ha,L+"}\n"];xe.push(rf);m=hb(xe)(...D);u=eb(u,m);m=b-1;if(!f.hasOwnProperty(p))throw new Ua("Replacing nonexistent public symbol");void 0!==f[p].Dh&&void 0!==m?f[p].Dh[m]=u:(f[p]=u,f[p].ji=m);return[]})},
j:(a,b,c,d,e)=>{b=C(b);-1===e&&(e=4294967295);e=l=>l;if(0===d){var g=32-8*c;e=l=>l<<g>>>g}var h=b.includes("unsigned")?function(l,m){return m>>>0}:function(l,m){return m};F(a,{name:b,fromWireType:e,toWireType:h,Kh:8,readValueFromPointer:tb(b,c,0!==d),Gh:null})},d:(a,b,c)=>{function d(g){return new e(n.buffer,t[g+4>>2],t[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=C(c);F(a,{name:c,fromWireType:d,Kh:8,readValueFromPointer:d},{Gi:!0})},
Ka:(a,b)=>{b=C(b);var c="std::string"===b;F(a,{name:b,fromWireType:function(d){var e=t[d>>2],g=d+4;if(c)for(var h=g,l=0;l<=e;++l){var m=g+l;if(l==e||0==q[m]){h=h?A(q,h,m-h):"";if(void 0===p)var p=h;else p+=String.fromCharCode(0),p+=h;h=m+1}}else{p=Array(e);for(l=0;l<e;++l)p[l]=String.fromCharCode(q[g+l]);p=p.join("")}G(d);return p},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g="string"==typeof e;if(!(g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof
Int8Array))throw new E("Cannot pass non-string to std::string");var h=c&&g?ub(e):e.length;var l=y(4+h+1),m=l+4;t[l>>2]=h;if(c&&g)z(e,m,h+1);else if(g)for(g=0;g<h;++g){var p=e.charCodeAt(g);if(255<p)throw G(m),new E("String has UTF-16 code units that do not fit in 8 bits");q[m+g]=p}else for(g=0;g<h;++g)q[m+g]=e[g];null!==d&&d.push(G,l);return l},Kh:8,readValueFromPointer:$a,Gh(d){G(d)}})},M:(a,b,c)=>{c=C(c);if(2===b){var d=wb;var e=xb;var g=yb;var h=l=>qa[l>>1]}else 4===b&&(d=zb,e=Ab,g=Bb,h=l=>t[l>>
2]);F(a,{name:c,fromWireType:l=>{for(var m=t[l>>2],p,u=l+4,D=0;D<=m;++D){var w=l+4+D*b;if(D==m||0==h(w))u=d(u,w-u),void 0===p?p=u:(p+=String.fromCharCode(0),p+=u),u=w+b}G(l);return p},toWireType:(l,m)=>{if("string"!=typeof m)throw new E(`Cannot pass non-string to C++ string type ${c}`);var p=g(m),u=y(4+p+b);t[u>>2]=p/b;e(m,u+4,p+b);null!==l&&l.push(G,u);return u},Kh:8,readValueFromPointer:$a,Gh(l){G(l)}})},fh:(a,b)=>{b=C(b);F(a,{Zi:!0,name:b,Kh:0,fromWireType:()=>{},toWireType:()=>{}})},vb:()=>1,
wb:(a,b,c)=>q.copyWithin(a,b,b+c),ib:()=>{Ka=!1;Cb=0},jb:(a,b)=>{Db[a]&&(clearTimeout(Db[a].id),delete Db[a]);if(!b)return 0;var c=setTimeout(()=>{delete Db[a];Hb(()=>of(a,performance.now()))},b);Db[a]={id:c,fj:b};return 0},kb:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();t[a>>2]=60*Math.max(g,e);r[b>>2]=Number(g!=e);b=h=>{var l=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,
"0")}`};a=b(g);b=b(e);e<g?(z(a,c,17),z(b,d,17)):(z(a,d,17),z(b,c,17))},Rd:a=>{if(12448==a)return H=12288,1;H=12300;return 0},eg:(a,b,c,d,e)=>{if(62E3!=a)H=12296,c=0;else{if(b)for(;;){a=r[b>>2];if(12321==a)I.alpha=0<r[b+4>>2];else if(12325==a)I.depth=0<r[b+4>>2];else if(12326==a)I.stencil=0<r[b+4>>2];else if(12337==a)a=r[b+4>>2],I.antialias=0<a;else if(12338==a)a=r[b+4>>2],I.antialias=1==a;else if(12544==a)I.$i=12547!=r[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(r[e>>2]=1),c&&0<d&&(t[c>>2]=62002),
H=12288,c=1):(H=12300,c=0)}return c},Jf:(a,b,c,d)=>{if(62E3!=a)return H=12296,0;for(a=1;;){b=r[d>>2];if(12440==b)a=r[d+4>>2];else if(12344==b)break;else return H=12292,0;d+=8}if(2>a||3<a)return H=12293,0;I.oi=a-1;I.bj=0;Zb=pc(f.canvas,I);if(0!=Zb)return H=12288,rc(Zb),Kb.forEach(e=>e()),rc(null),62004;H=12297;return 0},nf:(a,b)=>{if(62E3!=a)return H=12296,0;if(62002!=b)return H=12293,0;H=12288;return 62006},yf:(a,b)=>{if(62E3!=a)return H=12296,0;if(62004!=b)return H=12294,0;a=Zb;S===N[a]&&(S=null);
"object"==typeof V&&V.Ki(N[a].Hh.canvas);N[a]&&N[a].Hh.canvas&&(N[a].Hh.canvas.Lh=void 0);N[a]=null;H=12288;Vb==b&&(Vb=0);return 1},bf:(a,b)=>{if(62E3!=a)return H=12296,0;if(62006!=b)return H=12301,1;Wb==b&&(Wb=0);Xb==b&&(Xb=0);H=12288;return 1},Vf:(a,b,c,d)=>{if(62E3!=a)return H=12296,0;if(62002!=b)return H=12293,0;if(!d)return H=12300,0;H=12288;switch(c){case 12320:return r[d>>2]=I.alpha?32:24,1;case 12321:return r[d>>2]=I.alpha?8:0,1;case 12322:return r[d>>2]=8,1;case 12323:return r[d>>2]=8,1;
case 12324:return r[d>>2]=8,1;case 12325:return r[d>>2]=I.depth?24:0,1;case 12326:return r[d>>2]=I.stencil?8:0,1;case 12327:return r[d>>2]=12344,1;case 12328:return r[d>>2]=62002,1;case 12329:return r[d>>2]=0,1;case 12330:return r[d>>2]=4096,1;case 12331:return r[d>>2]=16777216,1;case 12332:return r[d>>2]=4096,1;case 12333:return r[d>>2]=0,1;case 12334:return r[d>>2]=0,1;case 12335:return r[d>>2]=12344,1;case 12337:return r[d>>2]=I.antialias?4:0,1;case 12338:return r[d>>2]=I.antialias?1:0,1;case 12339:return r[d>>
2]=4,1;case 12340:return r[d>>2]=12344,1;case 12341:case 12342:case 12343:return r[d>>2]=-1,1;case 12345:case 12346:return r[d>>2]=0,1;case 12347:return r[d>>2]=0,1;case 12348:return r[d>>2]=1;case 12349:case 12350:return r[d>>2]=0,1;case 12351:return r[d>>2]=12430,1;case 12352:return r[d>>2]=4,1;case 12354:return r[d>>2]=0,1;default:return H=12292,0}},La:a=>{H=12288;return 0!=a&&1!=a?0:62E3},vd:()=>H,Ag:(a,b,c)=>{if(62E3!=a)return H=12296,0;b&&(r[b>>2]=1);c&&(r[c>>2]=4);Ub=!0;H=12288;return 1},Se:(a,
b,c,d)=>{if(62E3!=a)return H=12296,0;if(0!=d&&62004!=d)return H=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return H=12301,0;rc(d?Zb:null);Vb=d;Xb=b;Wb=c;H=12288;return 1},Gd:(a,b)=>{if(62E3!=a)return H=12296,0;H=12288;if(Yb[b])return Yb[b];switch(b){case 12371:a=T("Emscripten");break;case 12372:a=T("1.4 Emscripten EGL");break;case 12373:a=T("");break;case 12429:a=T("OpenGL_ES");break;default:return H=12300,0}return Yb[b]=a},He:()=>{if(Ub)if(f.Eh)if(f.Eh.isContextLost())H=12302;else return H=12288,
1;else H=12290;else H=12289;return 0},we:(a,b)=>{if(62E3!=a)return H=12296,0;0==b?Ic(0,0):Ic(1,b);H=12288;return 1},pg:a=>{if(62E3!=a)return H=12296,0;Xb=Wb=Vb=0;Ub=!1;H=12288;return 1},ae:()=>{H=12288;return 1},le:()=>{H=12288;return 1},C:(a,b,c)=>{b=Pc(b,c);return Ga[a](...b)},_g:(a,b,c)=>{b=Pc(b,c);return Ga[a](...b)},Va:()=>{Kc();uc=null},Fa:()=>Date.now(),ab:()=>{if(!V.fullscreenEnabled())return-1;Sc(jd);var a=Xc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&
a.webkitExitFullscreen();else return-1;return 0},Rc:()=>{Sc(kd);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},ka:Yc,B:()=>devicePixelRatio,t:(a,b,c)=>{a=X(a);if(!a)return-4;a=hd(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},la:(a,b)=>{if(0>a||a>=V.Ph.length)return-5;if(!V.Ph[a])return-7;ld(b,V.Ph[a]);return 0},J:()=>performance.now(),$a:()=>V.Ph.length,kd:(a,b)=>{r[a>>2]=screen.width;r[b>>2]=screen.height},Cg:md,Bg:nd,id:(a,b)=>{J.beginQuery(a,O[b])},Sg:(a,b)=>{J.Ah.beginQueryEXT(a,
O[b])},Qc:a=>J.beginTransformFeedback(a),zg:(a,b,c)=>{J.bindAttribLocation(K[a],b,c?A(q,c):"")},yg:od,Nc:pd,Oc:qd,xg:rd,wg:(a,b)=>{J.bindRenderbuffer(a,dc[b])},Vb:(a,b)=>{J.bindSampler(a,Q[b])},vg:sd,Nb:(a,b)=>{J.bindTransformFeedback(a,gc[b])},Wc:td,Kg:td,ug:(a,b,c,d)=>J.blendColor(a,b,c,d),tg:ud,sg:vd,rg:(a,b)=>J.blendFunc(a,b),qg:wd,Zc:(a,b,c,d,e,g,h,l,m,p)=>J.blitFramebuffer(a,b,c,d,e,g,h,l,m,p),og:xd,ng:yd,mg:zd,lg:Ad,qc:(a,b,c,d)=>J.clearBufferfi(a,b,c,d),rc:Bd,tc:(a,b,c)=>{J.clearBufferiv(a,
b,r,c>>2)},sc:Cd,kg:Dd,jg:a=>J.clearDepth(a),ig:a=>J.clearStencil(a),cc:(a,b,c,d)=>J.clientWaitSync(hc[a],b,(c>>>0)+4294967296*d),Ed:(a,b)=>{J.Ci.clipControlEXT(a,b)},hg:(a,b,c,d)=>{J.colorMask(!!a,!!b,!!c,!!d)},gg:Ed,fg:(a,b,c,d,e,g,h,l)=>{J.Fh||!h?J.compressedTexImage2D(a,b,c,d,e,g,h,l):J.compressedTexImage2D(a,b,c,d,e,g,q,l,h)},od:(a,b,c,d,e,g,h,l,m)=>{J.Fh?J.compressedTexImage3D(a,b,c,d,e,g,h,l,m):J.compressedTexImage3D(a,b,c,d,e,g,h,q,m,l)},dg:(a,b,c,d,e,g,h,l,m)=>{J.Fh||!l?J.compressedTexSubImage2D(a,
b,c,d,e,g,h,l,m):J.compressedTexSubImage2D(a,b,c,d,e,g,h,q,m,l)},nd:(a,b,c,d,e,g,h,l,m,p,u)=>{J.Fh?J.compressedTexSubImage3D(a,b,c,d,e,g,h,l,m,p,u):J.compressedTexSubImage3D(a,b,c,d,e,g,h,l,m,q,u,p)},oc:(a,b,c,d,e)=>J.copyBufferSubData(a,b,c,d,e),cg:(a,b,c,d,e,g,h,l)=>J.copyTexImage2D(a,b,c,d,e,g,h,l),bg:(a,b,c,d,e,g,h,l)=>J.copyTexSubImage2D(a,b,c,d,e,g,h,l),pd:(a,b,c,d,e,g,h,l,m)=>J.copyTexSubImage3D(a,b,c,d,e,g,h,l,m),ag:Fd,$f:Gd,_f:Hd,Zf:Id,Yf:Jd,Xf:Kd,ld:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+
4*c>>2],e=O[d];e&&(J.deleteQuery(e),O[d]=null)}},Ug:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=O[d];e&&(J.Ah.deleteQueryEXT(e),O[d]=null)}},Wf:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=dc[d];e&&(J.deleteRenderbuffer(e),e.name=0,dc[d]=null)}},Xb:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Q[d];e&&(J.deleteSampler(e),e.name=0,Q[d]=null)}},Uf:Ld,dc:a=>{if(a){var b=hc[a];b?(J.deleteSync(b),b.name=0,hc[a]=null):R||=1281}},Tf:Md,Mb:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=gc[d];
e&&(J.deleteTransformFeedback(e),e.name=0,gc[d]=null)}},Vc:Nd,Jg:Nd,Sf:Od,Rf:a=>{J.depthMask(!!a)},Qf:(a,b)=>J.depthRange(a,b),Pf:Pd,Of:Qd,Nf:a=>{J.disableVertexAttribArray(a)},Mf:Rd,hc:Sd,Fg:Sd,zd:Sd,Ad:Sd,yb:Sd,ed:Ud,ud:Ud,Gg:Ud,Lf:Vd,gc:Wd,Eg:Wd,wd:Wd,xd:Wd,yd:Wd,sd:(a,b,c,d,e,g)=>{J.drawElements(a,d,e,g)},If:Xd,Hf:Yd,hd:a=>J.endQuery(a),Rg:a=>{J.Ah.endQueryEXT(a)},Pc:()=>J.endTransformFeedback(),fc:(a,b)=>(a=J.fenceSync(a,b))?(b=mc(hc),a.name=b,hc[b]=a,b):0,Gf:()=>J.finish(),Ff:()=>J.flush(),
Ef:(a,b,c,d)=>{J.framebufferRenderbuffer(a,b,c,dc[d])},Df:Zd,Xc:$d,Cf:a=>J.frontFace(a),Bf:ae,zf:be,md:(a,b)=>{nc(a,b,"createQuery",O)},Vg:(a,b)=>{for(var c=0;c<a;c++){var d=J.Ah.createQueryEXT();if(!d){for(R||=1282;c<a;)r[b+4*c++>>2]=0;break}var e=mc(O);d.name=e;O[e]=d;r[b+4*c>>2]=e}},xf:(a,b)=>{nc(a,b,"createRenderbuffer",dc)},Yb:(a,b)=>{nc(a,b,"createSampler",Q)},wf:ce,Lb:(a,b)=>{nc(a,b,"createTransformFeedback",gc)},Uc:de,Ig:de,Af:a=>J.generateMipmap(a),vf:(a,b,c,d,e,g,h)=>{ee("getActiveAttrib",
a,b,c,d,e,g,h)},uf:(a,b,c,d,e,g,h)=>{ee("getActiveUniform",a,b,c,d,e,g,h)},jc:(a,b,c,d,e)=>{a=K[a];if(a=J.getActiveUniformBlockName(a,b))e&&0<c?(c=z(a,e,c),d&&(r[d>>2]=c)):d&&(r[d>>2]=0)},kc:(a,b,c,d)=>{if(d)if(a=K[a],35393==c)r[d>>2]=J.getActiveUniformBlockName(a,b).length+1;else{if(a=J.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)r[d+4*c>>2]=a[c];else r[d>>2]=a}else R||=1281},mc:(a,b,c,d,e)=>{if(e)if(0<b&&0==c)R||=1281;else{a=K[a];for(var g=[],h=0;h<b;h++)g.push(r[c+
4*h>>2]);if(a=J.getActiveUniforms(a,g,d))for(b=a.length,h=0;h<b;h++)r[e+4*h>>2]=a[h]}else R||=1281},tf:(a,b,c,d)=>{a=J.getAttachedShaders(K[a]);var e=a.length;e>b&&(e=b);r[c>>2]=e;for(b=0;b<e;++b)r[d+4*b>>2]=M.indexOf(a[b])},sf:fe,rf:(a,b)=>ie(a,b,4),Zb:(a,b,c)=>{c?ge(c,J.getBufferParameter(a,b)):R||=1281},qf:(a,b,c)=>{c?r[c>>2]=J.getBufferParameter(a,b):R||=1281},pf:()=>{var a=J.getError()||R;R=0;return a},of:(a,b)=>ie(a,b,2),Cc:(a,b)=>J.getFragDataLocation(K[a],b?A(q,b):""),mf:(a,b,c,d)=>{a=J.getFramebufferAttachmentParameter(a,
b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;r[d>>2]=a},_b:(a,b,c)=>je(a,b,c,1),ac:(a,b)=>{ie(a,b,1)},Sc:(a,b,c)=>je(a,b,c,0),lf:ke,Ab:(a,b,c,d,e)=>{if(0>d)R||=1281;else if(e){if(a=J.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)r[e+4*b>>2]=a[b]}else R||=1281},Hb:()=>{R||=1282},jf:le,kf:me,Mg:ne,Og:oe,Lg:ne,fd:(a,b,c)=>{if(c){a=J.getQueryParameter(O[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;r[c>>2]=d}else R||=1281},Ng:oe,gd:(a,b,c)=>{c?r[c>>
2]=J.getQuery(a,b):R||=1281},Pg:(a,b,c)=>{c?r[c>>2]=J.Ah.getQueryEXT(a,b):R||=1281},hf:(a,b,c)=>{c?r[c>>2]=J.getRenderbufferParameter(a,b):R||=1281},Pb:(a,b,c)=>{c?v[c>>2]=J.getSamplerParameter(Q[a],b):R||=1281},Qb:(a,b,c)=>{c?r[c>>2]=J.getSamplerParameter(Q[a],b):R||=1281},ff:pe,ef:(a,b,c,d)=>{a=J.getShaderPrecisionFormat(a,b);r[c>>2]=a.rangeMin;r[c+4>>2]=a.rangeMax;r[d>>2]=a.precision},df:(a,b,c,d)=>{if(a=J.getShaderSource(M[a]))b=0<b&&d?z(a,d,b):0,c&&(r[c>>2]=b)},gf:qe,cf:a=>{var b=ic[a];if(!b){switch(a){case 7939:b=
T(he().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=J.getParameter(a))||(R||=1280);b=b?T(b):0;break;case 7938:b=T(`OpenGL ES 3.0 (${J.getParameter(7938)})`);break;case 35724:b=J.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=T(b);break;default:R||=1280}ic[a]=b}return b},pc:(a,b)=>{if(2>S.version)return R||=1282,0;var c=jc[a];if(c)return 0>b||b>=c.length?(R||=1281,0):c[b];
switch(a){case 7939:return c=he().map(T),c=jc[a]=c,0>b||b>=c.length?(R||=1281,0):c[b];default:return R||=1280,0}},$b:(a,b,c,d,e)=>{0>c?R||=1281:e?(a=J.getSyncParameter(hc[a],b),null!==a&&(r[e>>2]=a,d&&(r[d>>2]=1))):R||=1281},af:(a,b,c)=>{c?v[c>>2]=J.getTexParameter(a,b):R||=1281},$e:(a,b,c)=>{c?r[c>>2]=J.getTexParameter(a,b):R||=1281},Lc:(a,b,c,d,e,g,h)=>{a=K[a];if(a=J.getTransformFeedbackVarying(a,b))h&&0<c?(c=z(a.name,h,c),d&&(r[d>>2]=c)):d&&(r[d>>2]=0),e&&(r[e>>2]=a.size),g&&(r[g>>2]=a.type)},
lc:re,nc:(a,b,c,d)=>{if(d)if(0<b&&(0==c||0==d))R||=1281;else{a=K[a];for(var e=[],g=0;g<b;g++)e.push(Oa(r[c+4*g>>2]));if(a=J.getUniformIndices(a,e))for(b=a.length,g=0;g<b;g++)r[d+4*g>>2]=a[g]}else R||=1281},Ye:ue,_e:(a,b,c)=>{ve(a,b,c,2)},Ze:(a,b,c)=>{ve(a,b,c,0)},Dc:(a,b,c)=>ve(a,b,c,0),Jc:ye,Ic:ye,Ve:(a,b,c)=>{c?r[c>>2]=J.getVertexAttribOffset(a,b):R||=1281},Xe:(a,b,c)=>{we(a,b,c,2)},We:(a,b,c)=>{we(a,b,c,5)},Ue:(a,b)=>J.hint(a,b),Eb:(a,b,c)=>{for(var d=Td[b],e=0;e<b;e++)d[e]=r[c+4*e>>2];J.invalidateFramebuffer(a,
d)},Db:(a,b,c,d,e,g,h)=>{for(var l=Td[b],m=0;m<b;m++)l[m]=r[c+4*m>>2];J.invalidateSubFramebuffer(a,l,d,e,g,h)},Te:a=>(a=bc[a])?J.isBuffer(a):0,Re:ze,Qe:a=>(a=cc[a])?J.isFramebuffer(a):0,Pe:Ae,jd:a=>(a=O[a])?J.isQuery(a):0,Tg:a=>(a=O[a])?J.Ah.isQueryEXT(a):0,Oe:a=>(a=dc[a])?J.isRenderbuffer(a):0,Wb:a=>(a=Q[a])?J.isSampler(a):0,Ne:a=>(a=M[a])?J.isShader(a):0,ec:a=>J.isSync(hc[a]),Me:a=>(a=ec[a])?J.isTexture(a):0,Kb:a=>J.isTransformFeedback(gc[a]),Tc:Be,Hg:Be,Le:a=>J.lineWidth(a),Ke:Ce,Jb:()=>J.pauseTransformFeedback(),
Je:(a,b)=>{3317==a?kc=b:3314==a&&(lc=b);J.pixelStorei(a,b)},Dd:(a,b)=>{J.Mi.polygonModeWEBGL(a,b)},Ie:(a,b)=>J.polygonOffset(a,b),Fd:(a,b,c)=>{J.Di.polygonOffsetClampEXT(a,b,c)},Gb:()=>{R||=1280},Fb:()=>{R||=1280},Qg:(a,b)=>{J.Ah.queryCounterEXT(O[a],b)},td:De,Ge:(a,b,c,d,e,g,h)=>{if(J.Wh)J.readPixels(a,b,c,d,e,g,h);else{var l=Ee(g);h>>>=31-Math.clz32(l.BYTES_PER_ELEMENT);J.readPixels(a,b,c,d,e,g,l,h)}},Fe:()=>{},Ee:(a,b,c,d)=>J.renderbufferStorage(a,b,c,d),Yc:(a,b,c,d,e)=>J.renderbufferStorageMultisample(a,
b,c,d,e),Ib:()=>J.resumeTransformFeedback(),De:(a,b)=>{J.sampleCoverage(a,!!b)},Sb:(a,b,c)=>{J.samplerParameterf(Q[a],b,c)},Rb:(a,b,c)=>{J.samplerParameterf(Q[a],b,v[c>>2])},Ub:(a,b,c)=>{J.samplerParameteri(Q[a],b,c)},Tb:(a,b,c)=>{J.samplerParameteri(Q[a],b,r[c>>2])},Ce:Ge,Be:()=>{R||=1280},Ae:He,ze:(a,b,c)=>J.stencilFunc(a,b,c),ye:(a,b,c,d)=>J.stencilFuncSeparate(a,b,c,d),xe:a=>J.stencilMask(a),ve:(a,b)=>J.stencilMaskSeparate(a,b),ue:(a,b,c)=>J.stencilOp(a,b,c),te:(a,b,c,d)=>J.stencilOpSeparate(a,
b,c,d),se:Ie,rd:Je,re:(a,b,c)=>J.texParameterf(a,b,c),qe:(a,b,c)=>{J.texParameterf(a,b,v[c>>2])},pe:Ke,oe:(a,b,c)=>{J.texParameteri(a,b,r[c>>2])},Cb:(a,b,c,d,e)=>J.texStorage2D(a,b,c,d,e),Bb:(a,b,c,d,e,g)=>J.texStorage3D(a,b,c,d,e,g),ne:(a,b,c,d,e,g,h,l,m)=>{if(J.Fh)J.texSubImage2D(a,b,c,d,e,g,h,l,m);else if(m){var p=Ee(l);J.texSubImage2D(a,b,c,d,e,g,h,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else m=m?Fe(l,h,e,g,m):null,J.texSubImage2D(a,b,c,d,e,g,h,l,m)},qd:(a,b,c,d,e,g,h,l,m,p,u)=>{if(J.Fh)J.texSubImage3D(a,
b,c,d,e,g,h,l,m,p,u);else if(u){var D=Ee(p);J.texSubImage3D(a,b,c,d,e,g,h,l,m,p,D,u>>>31-Math.clz32(D.BYTES_PER_ELEMENT))}else J.texSubImage3D(a,b,c,d,e,g,h,l,m,p,null)},Mc:(a,b,c,d)=>{a=K[a];for(var e=[],g=0;g<b;g++)e.push(Oa(r[c+4*g>>2]));J.transformFeedbackVaryings(a,e,d)},me:(a,b)=>{J.uniform1f(Y(a),b)},ke:(a,b,c)=>{b&&J.uniform1fv(Y(a),v,c>>2,b)},je:Le,ie:(a,b,c)=>{b&&J.uniform1iv(Y(a),r,c>>2,b)},Bc:(a,b)=>{J.uniform1ui(Y(a),b)},xc:(a,b,c)=>{b&&J.uniform1uiv(Y(a),t,c>>2,b)},he:(a,b,c)=>{J.uniform2f(Y(a),
b,c)},ge:(a,b,c)=>{b&&J.uniform2fv(Y(a),v,c>>2,2*b)},fe:(a,b,c)=>{J.uniform2i(Y(a),b,c)},ee:(a,b,c)=>{b&&J.uniform2iv(Y(a),r,c>>2,2*b)},Ac:(a,b,c)=>{J.uniform2ui(Y(a),b,c)},wc:(a,b,c)=>{b&&J.uniform2uiv(Y(a),t,c>>2,2*b)},de:(a,b,c,d)=>{J.uniform3f(Y(a),b,c,d)},ce:(a,b,c)=>{b&&J.uniform3fv(Y(a),v,c>>2,3*b)},be:(a,b,c,d)=>{J.uniform3i(Y(a),b,c,d)},$d:(a,b,c)=>{b&&J.uniform3iv(Y(a),r,c>>2,3*b)},zc:(a,b,c,d)=>{J.uniform3ui(Y(a),b,c,d)},vc:(a,b,c)=>{b&&J.uniform3uiv(Y(a),t,c>>2,3*b)},_d:(a,b,c,d,e)=>{J.uniform4f(Y(a),
b,c,d,e)},Zd:(a,b,c)=>{b&&J.uniform4fv(Y(a),v,c>>2,4*b)},Yd:(a,b,c,d,e)=>{J.uniform4i(Y(a),b,c,d,e)},Xd:(a,b,c)=>{b&&J.uniform4iv(Y(a),r,c>>2,4*b)},yc:(a,b,c,d,e)=>{J.uniform4ui(Y(a),b,c,d,e)},uc:(a,b,c)=>{b&&J.uniform4uiv(Y(a),t,c>>2,4*b)},ic:Me,Wd:(a,b,c,d)=>{b&&J.uniformMatrix2fv(Y(a),!!c,v,d>>2,4*b)},dd:(a,b,c,d)=>{b&&J.uniformMatrix2x3fv(Y(a),!!c,v,d>>2,6*b)},bd:(a,b,c,d)=>{b&&J.uniformMatrix2x4fv(Y(a),!!c,v,d>>2,8*b)},Vd:(a,b,c,d)=>{b&&J.uniformMatrix3fv(Y(a),!!c,v,d>>2,9*b)},cd:(a,b,c,d)=>
{b&&J.uniformMatrix3x2fv(Y(a),!!c,v,d>>2,6*b)},$c:(a,b,c,d)=>{b&&J.uniformMatrix3x4fv(Y(a),!!c,v,d>>2,12*b)},Ud:Ne,ad:(a,b,c,d)=>{b&&J.uniformMatrix4x2fv(Y(a),!!c,v,d>>2,8*b)},_c:(a,b,c,d)=>{b&&J.uniformMatrix4x3fv(Y(a),!!c,v,d>>2,12*b)},Td:Oe,Sd:a=>{J.validateProgram(K[a])},Qd:(a,b)=>J.vertexAttrib1f(a,b),Pd:(a,b)=>{J.vertexAttrib1f(a,v[b>>2])},Od:(a,b,c)=>J.vertexAttrib2f(a,b,c),Nd:(a,b)=>{J.vertexAttrib2f(a,v[b>>2],v[b+4>>2])},Md:(a,b,c,d)=>J.vertexAttrib3f(a,b,c,d),Ld:(a,b)=>{J.vertexAttrib3f(a,
v[b>>2],v[b+4>>2],v[b+8>>2])},Kd:(a,b,c,d,e)=>J.vertexAttrib4f(a,b,c,d,e),Jd:(a,b)=>{J.vertexAttrib4f(a,v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},Ob:Pe,Dg:Pe,Bd:Pe,Cd:Pe,zb:Pe,Hc:(a,b,c,d,e)=>J.vertexAttribI4i(a,b,c,d,e),Fc:(a,b)=>{J.vertexAttribI4i(a,r[b>>2],r[b+4>>2],r[b+8>>2],r[b+12>>2])},Gc:(a,b,c,d,e)=>J.vertexAttribI4ui(a,b,c,d,e),Ec:(a,b)=>{J.vertexAttribI4ui(a,t[b>>2],t[b+4>>2],t[b+8>>2],t[b+12>>2])},Kc:Qe,Id:Re,Hd:Se,bc:(a,b,c,d)=>{J.waitSync(hc[a],b,(c>>>0)+4294967296*d)},Z:()=>0,bb:(a,b,
c)=>Te(a,{ci:r[c>>2],Vh:r[c+4>>2],Ei:r[c+8>>2],Ai:b,Oh:r[c+12>>2],li:r[c+16>>2]}),Ja:(a,b)=>{a=X(a);return a?a.requestPointerLock?Tc()?kd(a):b?(Rc(kd,2,[a]),1):-2:-1:-4},lb:a=>{var b=q.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ma.buffer.byteLength+65535)/65536|0;try{ma.grow(d);ra();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},ma:Ue,na:(a,b,c)=>"undefined"==typeof onbeforeunload?
-1:1!==c?-5:Ve(a,b),ya:(a,b,c,d)=>We(a,b,c,d,12,"blur"),A:dd,N:(a,b,c)=>{a=X(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},za:(a,b,c,d)=>We(a,b,c,d,13,"focus"),pa:(a,b,c,d)=>{if(!V.fullscreenEnabled())return-1;a=X(a);if(!a)return-4;Xe(a,b,c,d,"webkitfullscreenchange");return Xe(a,b,c,d,"fullscreenchange")},H:(a,b,c)=>Ue()?-1:Ye(a,b,c,26,"gamepadconnected"),G:(a,b,c)=>Ue()?-1:Ye(a,b,c,27,"gamepaddisconnected"),sa:(a,b,c,d)=>Ze(a,b,c,d,2,"keydown"),qa:(a,b,c,d)=>Ze(a,b,c,d,
1,"keypress"),ra:(a,b,c,d)=>Ze(a,b,c,d,3,"keyup"),ca:(a,b,c)=>{a=B(a);Jc(a,b,c)},Ha:(a,b,c,d)=>af(a,b,c,d,5,"mousedown"),Ea:(a,b,c,d)=>af(a,b,c,d,33,"mouseenter"),Ba:(a,b,c,d)=>af(a,b,c,d,34,"mouseleave"),Ia:(a,b,c,d)=>af(a,b,c,d,8,"mousemove"),Ga:(a,b,c,d)=>af(a,b,c,d,6,"mouseup"),ta:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Uh||document.body.Pi||document.body.Oi))return-1;a=X(a);if(!a)return-4;bf(a,b,c,d,"mozpointerlockchange");bf(a,b,c,d,"webkitpointerlockchange");
bf(a,b,c,d,"mspointerlockchange");return bf(a,b,c,d,"pointerlockchange")},I:(a,b,c,d)=>cf(a,b,c,d),ua:(a,b,c,d)=>df(a,b,c,d,25,"touchcancel"),wa:(a,b,c,d)=>df(a,b,c,d,23,"touchend"),va:(a,b,c,d)=>df(a,b,c,d,24,"touchmove"),xa:(a,b,c,d)=>df(a,b,c,d,22,"touchstart"),oa:(a,b,c)=>ef(a,b,c),Aa:(a,b,c,d)=>(a=X(a))?"undefined"!=typeof a.onwheel?ff(a,b,c,d):-1:-4,cb:a=>document.title=a?A(q,a):"",S:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";
},tb:(a,b)=>{var c=0;jf().forEach((d,e)=>{var g=b+c;e=t[a+4*e>>2]=g;for(g=0;g<d.length;++g)n[e++]=d.charCodeAt(g);n[e]=0;c+=d.length+1});return 0},ub:(a,b)=>{var c=jf();t[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);t[b>>2]=d;return 0},Ca:()=>52,qb:()=>52,eb:function(){return 70},pb:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var h=t[b>>2],l=t[b+4>>2];b+=8;for(var m=0;m<l;m++){var p=a,u=q[h+m],D=kf[p];0===u||10===u?((1===p?ha:ia)(A(D)),D.length=0):D.push(u)}e+=l}t[d>>2]=e;return 0},Q:md,V:nd,b:od,
K:pd,Ua:qd,v:rd,f:sd,x:td,P:td,Yg:ud,Zg:vd,Na:wd,e:xd,u:yd,l:zd,ba:Ad,dh:Bd,eh:Cd,Wa:Dd,W:Ed,Ra:Fd,Y:Gd,L:Hd,h:Id,F:Jd,T:Kd,U:Ld,k:Md,ga:Nd,ah:Nd,Xa:Od,Ma:Pd,o:Qd,fa:Rd,aa:Sd,da:Ud,bh:Vd,g:Xd,n:Yd,s:Zd,Ya:$d,i:ae,ea:be,z:ce,ja:de,ch:de,O:fe,a:ke,Sa:le,_:me,Ta:pe,$:qe,q:re,R:ue,D:ze,$g:Ae,Qa:Ce,Za:De,Oa:Ge,X:He,m:Ie,_a:Je,c:Ke,Pa:Le,p:Me,Xg:Ne,y:Oe,ha:Qe,w:Re,E:Se,hb:Fb},Z=function(){function a(c){Z=c.exports;ma=Z.gh;ra();Ma=Z.lh;ta.unshift(Z.hh);wa--;f.monitorRunDependencies?.(wa);0==wa&&(null!==
xa&&(clearInterval(xa),xa=null),ya&&(c=ya,ya=null,c()));return Z}var b={a:pf};wa++;f.monitorRunDependencies?.(wa);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){ia(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}Ba??=f.locateFile?Aa("wasmInterface.wasm")?"wasmInterface.wasm":f.locateFile?f.locateFile("wasmInterface.wasm",k):k+"wasmInterface.wasm":(new URL("wasmInterface.wasm",import.meta.url)).href;Fa(b,function(c){a(c.instance)}).catch(ba);return{}}(),
pb=a=>(pb=Z.ih)(a),G=a=>(G=Z.jh)(a),y=a=>(y=Z.kh)(a),of=(a,b)=>(of=Z.mh)(a,b),bd=a=>(bd=Z.nh)(a),Zc=a=>(Zc=Z.oh)(a),ad=()=>(ad=Z.ph)();f.dynCall_jiji=(a,b,c,d,e)=>(f.dynCall_jiji=Z.qh)(a,b,c,d,e);f.dynCall_ji=(a,b)=>(f.dynCall_ji=Z.rh)(a,b);f.dynCall_vij=(a,b,c,d)=>(f.dynCall_vij=Z.sh)(a,b,c,d);f.dynCall_viijii=(a,b,c,d,e,g,h)=>(f.dynCall_viijii=Z.th)(a,b,c,d,e,g,h);f.dynCall_iiiiij=(a,b,c,d,e,g,h)=>(f.dynCall_iiiiij=Z.uh)(a,b,c,d,e,g,h);
f.dynCall_iiiiijj=(a,b,c,d,e,g,h,l,m)=>(f.dynCall_iiiiijj=Z.vh)(a,b,c,d,e,g,h,l,m);f.dynCall_iiiiiijj=(a,b,c,d,e,g,h,l,m,p)=>(f.dynCall_iiiiiijj=Z.wh)(a,b,c,d,e,g,h,l,m,p);var qf;ya=function sf(){qf||tf();qf||(ya=sf)};
function tf(){function a(){if(!qf&&(qf=!0,f.calledRun=!0,!na)){Ja(ta);aa(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();ua.unshift(b)}Ja(ua)}}if(!(0<wa)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)va();Ja(sa);0<wa||(f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();tf();moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default Module;
