
var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

var g=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da=Object.assign({},g),ea="./this.program",l="",fa;"undefined"!=typeof document&&document.currentScript&&(l=document.currentScript.src);_scriptName&&(l=_scriptName);l.startsWith("blob:")?l="":l=l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1);fa=a=>fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var ha=g.print||console.log.bind(console),ia=g.printErr||console.error.bind(console);
Object.assign(g,da);da=null;g.thisProgram&&(ea=g.thisProgram);var ja=g.wasmBinary,ka,la=!1,ma,n,q,pa,qa,t,u,v,w;function ra(){var a=ka.buffer;g.HEAP8=n=new Int8Array(a);g.HEAP16=pa=new Int16Array(a);g.HEAPU8=q=new Uint8Array(a);g.HEAPU16=qa=new Uint16Array(a);g.HEAP32=t=new Int32Array(a);g.HEAPU32=u=new Uint32Array(a);g.HEAPF32=v=new Float32Array(a);g.HEAPF64=w=new Float64Array(a)}var sa=[],ta=[],ua=[];function va(){var a=g.preRun.shift();sa.unshift(a)}var wa=0,xa=null,ya=null;
function za(a){g.onAbort?.(a);a="Aborted("+a+")";ia(a);la=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Aa=a=>a.startsWith("data:application/octet-stream;base64,"),Ba;function Ca(a){if(a==Ba&&ja)return new Uint8Array(ja);throw"both async and sync fetching of the wasm failed";}function Da(a){return ja?Promise.resolve().then(()=>Ca(a)):fa(a).then(b=>new Uint8Array(b),()=>Ca(a))}
function Ea(a,b,c){return Da(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{ia(`failed to asynchronously prepare wasm: ${d}`);za(d)})}function Fa(a,b){var c=Ba;return ja||"function"!=typeof WebAssembly.instantiateStreaming||Aa(c)||"function"!=typeof fetch?Ea(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){ia(`wasm streaming compile failed: ${e}`);ia("falling back to ArrayBuffer instantiation");return Ea(c,a,b)}))}
var Ga={3499284:a=>{getBookHints(a)},3499306:a=>{checkDoorCode(a?x(q,a):"")},3499343:()=>window.innerWidth,3499373:()=>window.innerHeight,3499404:(a,b,c)=>{g.SDL2||(g.SDL2={});var d=g.SDL2;d.dj!==g.canvas&&(d.Zh=g.createContext(g.canvas,!1,!0),d.dj=g.canvas);if(d.w!==a||d.h!==b||d.tj!==d.Zh)d.image=d.Zh.createImageData(a,b),d.w=a,d.h=b,d.tj=d.Zh;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=t[b];a[e]=f&255;a[e+1]=f>>
8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.hj!==a&&(d.gj=new Int32Array(a.buffer),d.ij=new Uint8Array(a.buffer),d.hj=a),a=d.gj,c=a.length,a.set(t.subarray(b,b+c)),a=d.ij,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Zh.putImageData(d.image,0,0)},3500872:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var h=f.getContext("2d");
a=h.createImageData(a,b);b=a.data;e/=4;var k=0,m;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(m=b.length;k<m;){var p=t[e];b[k]=p&255;b[k+1]=p>>8&255;b[k+2]=p>>16&255;b[k+3]=p>>24&255;e++;k+=4}else b=new Int32Array(b.buffer),m=b.length,b.set(t.subarray(e,e+m));h.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=y(c.length+1);z(c,d,c.length+1);return d},3501860:a=>{g.canvas&&(g.canvas.style.cursor=a?x(q,a):"")},
3501943:()=>{g.canvas&&(g.canvas.style.cursor="none")}};class Ha{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ia=a=>{for(;0<a.length;)a.shift()(g)},Ja=g.noExitRuntime||!0,Ka=[],La,A=a=>{var b=Ka[a];b||(a>=Ka.length&&(Ka.length=a+1),Ka[a]=b=La.get(a));return b},Ma="undefined"!=typeof TextDecoder?new TextDecoder:void 0,x=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ma)return Ma.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|
h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Na=(a,b)=>a?x(q,a,b):"",Qa,D=a=>{for(var b="";q[a];)b+=Qa[q[a++]];return b},Ra={},Sa={},Ta={},E,Ua=a=>{throw new E(a);},Va,Wa=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new Va("Mismatched type converter count");for(var m=0;m<a.length;++m)F(a[m],k[m])}a.forEach(k=>Ta[k]=b);var e=Array(b.length),f=[],h=0;b.forEach((k,m)=>{Sa.hasOwnProperty(k)?
e[m]=Sa[k]:(f.push(k),Ra.hasOwnProperty(k)||(Ra[k]=[]),Ra[k].push(()=>{e[m]=Sa[k];++h;h===f.length&&d(e)}))});0===f.length&&d(e)};function Xa(a,b,c={}){var d=b.name;if(!a)throw new E(`type "${d}" must have a positive integer typeid pointer`);if(Sa.hasOwnProperty(a)){if(c.sj)return;throw new E(`Cannot register type '${d}' twice`);}Sa[a]=b;delete Ta[a];Ra.hasOwnProperty(a)&&(b=Ra[a],delete Ra[a],b.forEach(e=>e()))}function F(a,b,c={}){return Xa(a,b,c)}
var Ya=a=>{throw new E(a.Lh.Oh.Mh.name+" instance already deleted");},Za=!1,$a=()=>{},ab=(a,b,c)=>{if(b===c)return a;if(void 0===c.Sh)return null;a=ab(a,b,c.Sh);return null===a?null:c.kj(a)},bb={},cb={},db=(a,b)=>{if(void 0===b)throw new E("ptr should not be undefined");for(;a.Sh;)b=a.ni(b),a=a.Sh;return cb[b]},fb=(a,b)=>{if(!b.Oh||!b.Nh)throw new Va("makeClassHandle requires ptr and ptrType");if(!!b.Th!==!!b.Rh)throw new Va("Both smartPtrType and smartPtr must be specified");b.count={value:1};return eb(Object.create(a,
{Lh:{value:b,writable:!0}}))},eb=a=>{if("undefined"===typeof FinalizationRegistry)return eb=b=>b,a;Za=new FinalizationRegistry(b=>{b=b.Lh;--b.count.value;0===b.count.value&&(b.Rh?b.Th.fi(b.Rh):b.Oh.Mh.fi(b.Nh))});eb=b=>{var c=b.Lh;c.Rh&&Za.register(b,{Lh:c},b);return b};$a=b=>{Za.unregister(b)};return eb(a)},gb=[];function hb(){}
var ib=(a,b)=>Object.defineProperty(b,"name",{value:a}),jb=(a,b,c)=>{if(void 0===a[b].Qh){var d=a[b];a[b]=function(...e){if(!a[b].Qh.hasOwnProperty(e.length))throw new E(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].Qh})!`);return a[b].Qh[e.length].apply(this,e)};a[b].Qh=[];a[b].Qh[d.ji]=d}},kb=(a,b,c)=>{if(g.hasOwnProperty(a)){if(void 0===c||void 0!==g[a].Qh&&void 0!==g[a].Qh[c])throw new E(`Cannot register public name '${a}' twice`);jb(g,a,a);
if(g[a].Qh.hasOwnProperty(c))throw new E(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);g[a].Qh[c]=b}else g[a]=b,g[a].ji=c},lb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function mb(a,b,c,d,e,f,h,k){this.name=a;this.constructor=b;this.hi=c;this.fi=d;this.Sh=e;this.pj=f;this.ni=h;this.kj=k;this.xj=[]}
var nb=(a,b,c)=>{for(;b!==c;){if(!b.ni)throw new E(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ni(a);b=b.Sh}return a};function ob(a,b){if(null===b){if(this.Fi)throw new E(`null is not a valid ${this.name}`);return 0}if(!b.Lh)throw new E(`Cannot pass "${pb(b)}" as a ${this.name}`);if(!b.Lh.Nh)throw new E(`Cannot pass deleted object as a pointer of type ${this.name}`);return nb(b.Lh.Nh,b.Lh.Oh.Mh,this.Mh)}
function qb(a,b){if(null===b){if(this.Fi)throw new E(`null is not a valid ${this.name}`);if(this.ti){var c=this.yj();null!==a&&a.push(this.fi,c);return c}return 0}if(!b||!b.Lh)throw new E(`Cannot pass "${pb(b)}" as a ${this.name}`);if(!b.Lh.Nh)throw new E(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.si&&b.Lh.Oh.si)throw new E(`Cannot convert argument of type ${b.Lh.Th?b.Lh.Th.name:b.Lh.Oh.name} to parameter type ${this.name}`);c=nb(b.Lh.Nh,b.Lh.Oh.Mh,this.Mh);if(this.ti){if(void 0===
b.Lh.Rh)throw new E("Passing raw pointer to smart pointer is illegal");switch(this.Bj){case 0:if(b.Lh.Th===this)c=b.Lh.Rh;else throw new E(`Cannot convert argument of type ${b.Lh.Th?b.Lh.Th.name:b.Lh.Oh.name} to parameter type ${this.name}`);break;case 1:c=b.Lh.Rh;break;case 2:if(b.Lh.Th===this)c=b.Lh.Rh;else{var d=b.clone();c=this.zj(c,rb(()=>d["delete"]()));null!==a&&a.push(this.fi,c)}break;default:throw new E("Unsupporting sharing policy");}}return c}
function sb(a,b){if(null===b){if(this.Fi)throw new E(`null is not a valid ${this.name}`);return 0}if(!b.Lh)throw new E(`Cannot pass "${pb(b)}" as a ${this.name}`);if(!b.Lh.Nh)throw new E(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.Lh.Oh.si)throw new E(`Cannot convert argument of type ${b.Lh.Oh.name} to parameter type ${this.name}`);return nb(b.Lh.Nh,b.Lh.Oh.Mh,this.Mh)}function tb(a){return this.fromWireType(u[a>>2])}
function ub(a,b,c,d,e,f,h,k,m,p,r){this.name=a;this.Mh=b;this.Fi=c;this.si=d;this.ti=e;this.vj=f;this.Bj=h;this.Yi=k;this.yj=m;this.zj=p;this.fi=r;e||void 0!==b.Sh?this.toWireType=qb:(this.toWireType=d?ob:sb,this.ai=null)}
var vb=(a,b,c)=>{if(!g.hasOwnProperty(a))throw new Va("Replacing nonexistent public symbol");void 0!==g[a].Qh&&void 0!==c?g[a].Qh[c]=b:(g[a]=b,g[a].ji=c)},wb=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,g["dynCall_"+a])(b,...c)):b=A(b)(...c);return b},xb=(a,b)=>(...c)=>wb(a,b,c),yb=(a,b)=>{a=D(a);var c=a.includes("j")?xb(a,b):A(b);if("function"!=typeof c)throw new E(`unknown function pointer with signature ${a}: ${b}`);return c},zb,Bb=a=>{a=Ab(a);var b=D(a);G(a);return b},Cb=(a,b)=>{function c(f){e[f]||
Sa[f]||(Ta[f]?Ta[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new zb(`${a}: `+d.map(Bb).join([", "]));},Db=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(u[b+4*d>>2]);return c},Eb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Fb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].ai)return!0;return!1}
function Gb(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=ib(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Hb(a,b,c,d,e,f){var h=b.length;if(2>h)throw new E("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,m=Fb(b);c="void"!==b[0].name;d=[a,Ua,d,e,Eb,b[0],b[1]];for(e=0;e<h-2;++e)d.push(b[e+2]);if(!m)for(e=k?1:2;e<b.length;++e)null!==b[e].ai&&d.push(b[e].ai);m=Fb(b);e=b.length-2;var p=[],r=["fn"];k&&r.push("thisWired");for(h=0;h<e;++h)p.push(`arg${h}`),r.push(`arg${h}Wired`);p=p.join(",");r=r.join(",");p=`return function (${p}) {\n`;m&&
(p+="var destructors = [];\n");var C=m?"destructors":"null",B="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");k&&(p+=`var thisWired = classParam['toWireType'](${C}, this);\n`);for(h=0;h<e;++h)p+=`var arg${h}Wired = argType${h}['toWireType'](${C}, arg${h});\n`,B.push(`argType${h}`);p+=(c||f?"var rv = ":"")+`invoker(${r});\n`;if(m)p+="runDestructors(destructors);\n";else for(h=k?1:2;h<b.length;++h)f=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==b[h].ai&&(p+=`${f}_dtor(${f});\n`,
B.push(`${f}_dtor`));c&&(p+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [K,H]=[B,p+"}\n"];K.push(H);b=Gb(K)(...d);return ib(a,b)}
var Ib=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Jb=[],Kb=[],rb=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Jb.pop()||Kb.length;Kb[b]=a;Kb[b+1]=1;return b}},Lb={name:"emscripten::val",fromWireType:a=>{if(!a)throw new E("Cannot use deleted val. handle = "+a);var b=Kb[a];9<a&&0===--Kb[a+1]&&(Kb[a]=void 0,Jb.push(a));return b},toWireType:(a,b)=>rb(b),ci:8,readValueFromPointer:tb,ai:null},pb=a=>{if(null===a)return"null";
var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},Mb=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(v[c>>2])};case 8:return function(c){return this.fromWireType(w[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Nb=(a,b,c)=>{switch(b){case 1:return c?d=>n[d]:d=>q[d];case 2:return c?d=>pa[d>>1]:d=>qa[d>>1];case 4:return c?d=>t[d>>2]:d=>u[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ob=Object.assign({optional:!0},
Lb),z=(a,b,c)=>{var d=q;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var k=a.charCodeAt(++f);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(b>=c)break;d[b++]=h}else{if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6}else{if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63}d[b++]=128|h>>6&63}d[b++]=128|h&63}}d[b]=0;return b-e},Pb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?
b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Qb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Rb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&qa[c];)++c;c<<=1;if(32<c-a&&Qb)return Qb.decode(q.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=pa[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Sb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)pa[b>>1]=a.charCodeAt(e),b+=2;pa[b>>1]=0;return b-d},Tb=
a=>2*a.length,Ub=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=t[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Vb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}t[b>>2]=f;b+=4;if(b+4>c)break}t[b>>2]=0;return b-d},Wb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=
d&&57343>=d&&++c;b+=4}return b},Xb=0,Yb={},Zb=a=>{if(!(a instanceof Ha||"unwind"==a))throw a;},$b=a=>{ma=a;Ja||0<Xb||(g.onExit?.(a),la=!0);throw new Ha(a);},ac=()=>{if(!(Ja||0<Xb))try{var a=ma;ma=a;$b(a)}catch(b){Zb(b)}},bc=a=>{if(!la)try{a(),ac()}catch(b){Zb(b)}},cc=!1,dc=!1,ec=[];
function fc(){function a(){dc=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}if(!gc){gc=!0;var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!dc&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}var hc=!1,ic=void 0,jc=void 0;
function kc(){if(!cc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var lc=[];function mc(){var a=g.canvas;lc.forEach(b=>b(a.width,a.height))}
function nc(a,b,c){b&&c?(a.Ej=b,a.rj=c):(b=a.Ej,c=a.rj);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}jc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var gc,I=12288,oc=!1,pc=0,qc=0,rc=0,J={alpha:!1,depth:!1,stencil:!1,antialias:!1},sc={},tc,L,uc=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},vc=1,wc=[],M=[],xc=[],yc=[],zc=[],N=[],Ac=[],O=[],P=[],Q=[],Bc=[],Cc=[],Dc={},Ec={},Fc=4,Gc=0,Hc=a=>{for(var b=vc++,c=a.length;c<b;c++)a[c]=null;return b},Ic=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=L[c](),h=f&&Hc(d);f?(f.name=h,d[h]=f):T||=1282;t[b+4*e>>2]=h}},Kc=(a,b)=>{a.oi||(a.oi=a.getContext,a.getContext=function(d,e){e=a.oi(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?
Jc(c,b):0},Jc=(a,b)=>{var c=Hc(O),d={handle:c,attributes:b,version:b.Vi,bi:a};a.canvas&&(a.canvas.ii=d);O[c]=d;("undefined"==typeof b.lj||b.lj)&&Lc(d);return c},Mc=a=>{U=O[a];g.Zh=L=U?.bi},Lc=a=>{a||=U;if(!a.uj){a.uj=!0;var b=a.bi;b.Sj=b.getExtension("WEBGL_multi_draw");b.nj=b.getExtension("EXT_polygon_offset_clamp");b.mj=b.getExtension("EXT_clip_control");b.Dj=b.getExtension("WEBGL_polygon_mode");b.Lj=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Qj=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Wh=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Wh)b.Wh=b.getExtension("EXT_disjoint_timer_query");uc(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},Nc={},T,U,Oc=a=>{var b=Pb(a)+1,c=y(b);c&&z(a,c,b);return c},ed=(a,b,c,d,e)=>{function f(){return h<Pc?(ac(),!1):!0}Qc=a;Rc=d;var h=Pc;Sc=!1;Tc=function(){if(!la)if(0<Uc.length){var k=Uc.shift();k.Nj(k.Fj);if(Vc){var m=Vc,p=0==m%1?m-1:Math.floor(m);Vc=k.Ij?p:(8*m+(p+.5))/
9}g.setStatus&&(k=g.statusMessage||"Please wait...",m=Vc??0,p=Wc.Mj??0,m?m<p?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(k):g.setStatus(""));f()&&setTimeout(Tc,0)}else if(f())if(Xc=Xc+1|0,1==Yc&&1<Zc&&0!=Xc%Zc)$c();else{0==Yc&&(ad=performance.now());a:if(!la){for(k of bd)if(!1===k())break a;bc(a);for(m of cd)m()}f()&&$c()}};e||(b&&0<b?dd(0,1E3/b):dd(1,1),$c());if(c)throw"unwind";},Sc=!1,$c=null,Pc=0,Qc=null,Rc=0,Yc=0,Zc=0,Xc=0,Uc=[],bd=[],cd=[];
function fd(){$c=null;Pc++}var gd=0;function hd(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===gd)gd=b+1E3/60;else for(;b+2>=gd;)gd+=1E3/60;setTimeout(a,Math.max(gd-b,0))}}
var Wc={},Tc,Vc,ad,jd,dd=(a,b)=>{Yc=a;Zc=b;if(Qc)if(Sc||=!0,0==a)$c=function(){setTimeout(Tc,Math.max(0,ad+b-performance.now())|0)};else if(1==a)$c=function(){hd(Tc)};else if(2==a){if("undefined"==typeof jd)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);jd=d=>{c.push(d);postMessage("setimmediate","*")}}else jd=setImmediate;$c=function(){jd(Tc)}}},kd=[],ld=(a,b)=>{kd.length=
0;for(var c;c=q[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;kd.push(112==c?u[b>>2]:105==c?t[b>>2]:w[b>>3]);b+=d?8:4}return kd};function md(a){var b=V.Xh[a];b.target.removeEventListener(b.Ph,b.Ti,b.Uh);V.Xh.splice(a,1)}function nd(a,b,c){function d(f,h){if(f.length!=h.length)return!1;for(var k in f)if(f[k]!=h[k])return!1;return!0}for(var e of V.di)if(e.Ji==a&&d(e.Qi,c))return;V.di.push({Ji:a,Xi:b,Qi:c});V.di.sort((f,h)=>f.Xi<h.Xi)}function od(a){V.di=V.di.filter(b=>b.Ji!=a)}
function pd(){return navigator.userActivation?navigator.userActivation.isActive:V.Ei&&V.ej.pi}function qd(){if(pd()){var a=V.di;V.di=[];for(var b of a)b.Ji(...b.Qi)}}function W(a){if(!a.target)return-4;if(a.Vh)a.Ti=function(c){++V.Ei;V.ej=a;qd();a.Yh(c);qd();--V.Ei},a.target.addEventListener(a.Ph,a.Ti,a.Uh),V.Xh.push(a);else for(var b=0;b<V.Xh.length;++b)V.Xh[b].target==a.target&&V.Xh[b].Ph==a.Ph&&md(b--);return 0}
function rd(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var V={Gj:0,Di:0,Gi:0,yi:0,Oi:0,Li:0,Bi:0,Kj:0,Tj:0,Jj:0,Ci:0,Hi:0,Ni:0,Ki:0,Uj(){for(;V.Xh.length;)md(V.Xh.length-1);V.di=[]},Ei:0,di:[],Xh:[],Aj:(a,b)=>{for(var c=0;c<V.Xh.length;++c)V.Xh[c].target!=a||b&&b!=V.Xh[c].Ph||md(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},sd={},td=[0,document,window],X=a=>{a=2<a?a?x(q,a):"":a;return td[a]||document.querySelector(a)},ud=(a,b,c)=>{a=X(a);if(!a)return-4;t[b>>2]=a.width;t[c>>2]=a.height},wd=a=>{var b=Pb(a)+
1,c=vd(b);z(a,c,b);return c},zd=a=>{var b=xd(),c=vd(8),d=c+4;a=wd(a.id);ud(a,c,d);c=[t[c>>2],t[d>>2]];yd(b);return c},Ad=(a,b,c)=>{a=X(a);if(!a)return-4;a.width=b;a.height=c;return 0},Bd=(a,b,c)=>{if(a.Hj){var d=xd();a=wd(a.id);Ad(a,b,c);yd(d)}else a.width=b,a.height=c},Cd=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Bd(a,d,e),a.style.width=f,a.style.height=
h,a.style.backgroundColor=k,m||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=m,a.style.paddingLeft=p,a.style.paddingRight=r,a.style.paddingTop=C,a.style.paddingBottom=B,a.style.marginLeft=K,a.style.marginRight=H,a.style.marginTop=R,a.style.marginBottom=na,document.body.style.margin=Oa,document.documentElement.style.overflow=S,document.body.scroll=oa,a.style.ei=Pa,a.ii&&a.ii.bi.viewport(0,0,d,e),sd.ri&&A(sd.ri)(37,0,sd.Ri))}var c=zd(a),d=c[0],e=c[1],f=a.style.width,
h=a.style.height,k=a.style.backgroundColor,m=document.body.style.backgroundColor,p=a.style.paddingLeft,r=a.style.paddingRight,C=a.style.paddingTop,B=a.style.paddingBottom,K=a.style.marginLeft,H=a.style.marginRight,R=a.style.marginTop,na=a.style.marginBottom,Oa=document.body.style.margin,S=document.documentElement.style.overflow,oa=document.body.scroll,Pa=a.style.ei;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},Dd=(a,b,c)=>{a.style.paddingLeft=
a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Ed=a=>0>td.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Fd=(a,b)=>{if(0!=b.Ii||0!=b.zi){Cd(a);var c=b.Cj?innerWidth:screen.width,d=b.Cj?innerHeight:screen.height,e=Ed(a),f=e.width;e=e.height;var h=zd(a),k=h[0];h=h[1];3==b.Ii?(Dd(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Ii&&(c*h<k*d?(f=h*c/k,Dd(a,(d-f)/2,0),d=f):(f=k*d/h,Dd(a,0,(c-f)/2),c=f));var m;(m=a.style).backgroundColor||(m.backgroundColor="black");let p;(p=document.body.style).backgroundColor||
(p.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.oj&&(a.style.ei="optimizeSpeed",a.style.ei="-moz-crisp-edges",a.style.ei="-o-crisp-edges",a.style.ei="-webkit-optimize-contrast",a.style.ei="optimize-contrast",a.style.ei="crisp-edges",a.style.ei="pixelated");m=2==b.zi?devicePixelRatio:1;0!=b.zi&&(c=c*m|0,d=d*m|0,Bd(a,c,d),a.ii&&a.ii.bi.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return V.fullscreenEnabled()?-3:-1;sd=b;b.ri&&A(b.ri)(37,0,b.Ri);return 0},Gd=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Hd=(a,b)=>{w[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)w[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)w[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)n[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
n[a+1104]=b.connected;t[a+1108>>2]=b.index;t[a+8>>2]=b.axes.length;t[a+12>>2]=b.buttons.length;z(b.id,a+1112,64);z(b.mapping,a+1176,64)},Id=a=>L.activeTexture(a),Jd=(a,b)=>{L.attachShader(M[a],N[b])},Kd=(a,b)=>{35051==a?L.Ai=b:35052==a&&(L.$h=b);L.bindBuffer(a,wc[b])},Ld=(a,b,c)=>{L.bindBufferBase(a,b,wc[c])},Md=(a,b,c,d,e)=>{L.bindBufferRange(a,b,wc[c],d,e)},Nd=(a,b)=>{L.bindFramebuffer(a,xc[b])},Od=(a,b)=>{L.bindTexture(a,zc[b])},Pd=a=>{L.bindVertexArray(Ac[a])},Qd=a=>L.blendEquation(a),Rd=(a,b)=>
L.blendEquationSeparate(a,b),Sd=(a,b,c,d)=>L.blendFuncSeparate(a,b,c,d),Td=(a,b,c,d)=>{c&&b?L.bufferData(a,q,d,c,b):L.bufferData(a,b,d)},Ud=(a,b,c,d)=>{c&&L.bufferSubData(a,b,q,d,c)},Vd=a=>L.checkFramebufferStatus(a),Wd=a=>L.clear(a),Xd=(a,b,c)=>{L.clearBufferfv(a,b,v,c>>2)},Yd=(a,b,c)=>{L.clearBufferuiv(a,b,u,c>>2)},Zd=(a,b,c,d)=>L.clearColor(a,b,c,d),$d=a=>{L.compileShader(N[a])},ae=()=>{var a=Hc(M),b=L.createProgram();b.name=a;b.xi=b.vi=b.wi=0;b.Mi=1;M[a]=b;return a},be=a=>{var b=Hc(N);N[b]=L.createShader(a);
return b},ce=a=>L.cullFace(a),de=(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=wc[d];e&&(L.deleteBuffer(e),e.name=0,wc[d]=null,d==L.Ai&&(L.Ai=0),d==L.$h&&(L.$h=0))}},ee=(a,b)=>{for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=xc[d];e&&(L.deleteFramebuffer(e),e.name=0,xc[d]=null)}},fe=a=>{if(a){var b=M[a];b?(L.deleteProgram(b),b.name=0,M[a]=null):T||=1281}},ge=a=>{if(a){var b=N[a];b?(L.deleteShader(b),N[a]=null):T||=1281}},he=(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=zc[d];e&&(L.deleteTexture(e),
e.name=0,zc[d]=null)}},ie=(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];L.deleteVertexArray(Ac[d]);Ac[d]=null}},je=a=>L.depthFunc(a),ke=(a,b)=>{L.detachShader(M[a],N[b])},le=a=>L.disable(a),me=(a,b,c)=>{L.drawArrays(a,b,c)},ne=(a,b,c,d)=>{L.drawArraysInstanced(a,b,c,d)},oe=[],pe=(a,b)=>{for(var c=oe[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];L.drawBuffers(c)},qe=(a,b,c,d)=>{L.drawElements(a,b,c,d)},re=(a,b,c,d,e)=>{L.drawElementsInstanced(a,b,c,d,e)},se=a=>L.enable(a),te=a=>{L.enableVertexAttribArray(a)},ue=
(a,b,c,d,e)=>{L.framebufferTexture2D(a,b,c,zc[d],e)},ve=(a,b,c,d,e)=>{L.framebufferTextureLayer(a,b,zc[c],d,e)},we=(a,b)=>{Ic(a,b,"createBuffer",wc)},xe=(a,b)=>{Ic(a,b,"createFramebuffer",xc)},ye=(a,b)=>{Ic(a,b,"createTexture",zc)},ze=(a,b)=>{Ic(a,b,"createVertexArray",Ac)},Ae=(a,b,c,d,e,f,h,k)=>{b=M[b];if(a=L[a](b,c))d=k&&z(a.name,k,d),e&&(t[e>>2]=d),f&&(t[f>>2]=a.size),h&&(t[h>>2]=a.type)},Be=(a,b)=>L.getAttribLocation(M[a],b?x(q,b):""),Ce=(a,b)=>{u[a>>2]=b;u[a+4>>2]=(b-u[a>>2])/4294967296};
function De(){var a=uc(L);return a=a.concat(a.map(b=>"GL_"+b))}
for(var Ee=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(T||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=L.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>U.version){T||=1282;return}d=De().length;break;case 33307:case 33308:if(2>U.version){T||=1280;return}d=33307==a?3:0}if(void 0===d)switch(e=L.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":T||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=
0;break;default:T||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:t[b+4*a>>2]=e[a];break;case 2:v[b+4*a>>2]=e[a];break;case 4:n[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){T||=1280;ia(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:T||=1280;ia(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:Ce(b,d);break;case 0:t[b>>2]=d;break;case 2:v[b>>2]=d;break;case 4:n[b]=d?1:0}}else T||=1281},Fe=(a,b,c,d)=>{if(c){b=L.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:T||=1280;return}else if(b instanceof WebGLBuffer)a=b.name|0;else{T||=1280;return}break;default:T||=1280;return}switch(d){case 1:Ce(c,a);break;case 0:t[c>>2]=a;break;case 2:v[c>>2]=a;break;
case 4:n[c]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else T||=1281},Ge=(a,b)=>Ee(a,b,0),He=(a,b,c,d)=>{a=L.getProgramInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?z(a,d,b):0;c&&(t[c>>2]=b)},Ie=(a,b,c)=>{if(c)if(a>=vc)T||=1281;else if(a=M[a],35716==b)a=L.getProgramInfoLog(a),null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b){if(!a.xi){var d=L.getProgramParameter(a,35718);for(b=0;b<d;++b)a.xi=Math.max(a.xi,L.getActiveUniform(a,
b).name.length+1)}t[c>>2]=a.xi}else if(35722==b){if(!a.vi)for(d=L.getProgramParameter(a,35721),b=0;b<d;++b)a.vi=Math.max(a.vi,L.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.vi}else if(35381==b){if(!a.wi)for(d=L.getProgramParameter(a,35382),b=0;b<d;++b)a.wi=Math.max(a.wi,L.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.wi}else t[c>>2]=L.getProgramParameter(a,b);else T||=1281},Je=(a,b,c)=>{if(c){a=P[a];b=2>U.version?L.Wh.getQueryObjectEXT(a,b):L.getQueryParameter(a,b);var d;"boolean"==typeof b?
d=b?1:0:d=b;Ce(c,d)}else T||=1281},Ke=(a,b,c)=>{if(c){a=L.Wh.getQueryObjectEXT(P[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d}else T||=1281},Le=(a,b,c,d)=>{a=L.getShaderInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?z(a,d,b):0;c&&(t[c>>2]=b)},Me=(a,b,c)=>{c?35716==b?(a=L.getShaderInfoLog(N[a]),null===a&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):35720==b?(a=L.getShaderSource(N[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=L.getShaderParameter(N[a],b):T||=1281},Ne=(a,b)=>L.getUniformBlockIndex(M[a],
b?x(q,b):""),Oe=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Pe=a=>{var b=a.mi,c=a.$i,d;if(!b){a.mi=b={};a.Zi={};var e=L.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=L.getActiveUniform(a,d);var h=f.name;f=f.size;var k=Oe(h);k=0<k?h.slice(0,k):h;var m=a.Mi;a.Mi+=f;c[k]=[f,m];for(h=0;h<f;++h)b[m]=h,a.Zi[m++]=k}}},Qe=(a,b)=>{b=b?x(q,b):"";if(a=M[a]){Pe(a);var c=a.mi,d=0,e=b,f=Oe(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.$i[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||L.getUniformLocation(a,
b)))return d}else T||=1281;return-1},Y=a=>{var b=L.fj;if(b){var c=b.mi[a];"number"==typeof c&&(b.mi[a]=c=L.getUniformLocation(b,b.Zi[a]+(0<c?`[${c}]`:"")));return c}T||=1282},Re=(a,b,c,d)=>{if(c)if(a=M[a],Pe(a),a=L.getUniform(a,Y(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:v[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:v[c+4*b>>2]=a[b]}else T||=1281},Se=(a,b,c,d)=>{if(c)if(a=L.getVertexAttrib(a,b),34975==b)t[c>>2]=a&&a.name;
else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:v[c>>2]=a;break;case 5:t[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:v[c+4*b>>2]=a[b];break;case 5:t[c+4*b>>2]=Math.fround(a[b])}else T||=1281},Te=(a,b,c)=>{Se(a,b,c,0)},Ue=a=>L.isEnabled(a),Ve=a=>(a=M[a])?L.isProgram(a):0,Xe=a=>(a=Ac[a])?L.isVertexArray(a):0,Ye=a=>{a=M[a];L.linkProgram(a);a.mi=0;a.$i={}},Ze=(a,b)=>{3317==a?Fc=b:3314==a&&(Gc=b);L.pixelStorei(a,
b)},$e=a=>L.readBuffer(a),af=a=>{a-=5120;return 0==a?n:1==a?q:2==a?pa:4==a?t:6==a?v:5==a||28922==a||28520==a||30779==a||30782==a?u:qa},bf=(a,b,c,d,e)=>{a=af(a);b=d*((Gc||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Fc-1&-Fc);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},cf=(a,b,c,d)=>L.scissor(a,b,c,d),df=(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=Na(u[c+4*f>>2],d?u[d+4*f>>2]:void 0);L.shaderSource(N[a],
e)},ef=(a,b,c,d,e,f,h,k,m)=>{if(L.$h)L.texImage2D(a,b,c,d,e,f,h,k,m);else if(m){var p=af(k);m>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);L.texImage2D(a,b,c,d,e,f,h,k,p,m)}else p=m?bf(k,h,d,e,m):null,L.texImage2D(a,b,c,d,e,f,h,k,p)},ff=(a,b,c,d,e,f,h,k,m,p)=>{if(L.$h)L.texImage3D(a,b,c,d,e,f,h,k,m,p);else if(p){var r=af(m);L.texImage3D(a,b,c,d,e,f,h,k,m,r,p>>>31-Math.clz32(r.BYTES_PER_ELEMENT))}else L.texImage3D(a,b,c,d,e,f,h,k,m,null)},gf=(a,b,c)=>L.texParameteri(a,b,c),hf=(a,b)=>{L.uniform1i(Y(a),b)},
jf=(a,b,c)=>{a=M[a];L.uniformBlockBinding(a,b,c)},kf=(a,b,c,d)=>{b&&L.uniformMatrix4fv(Y(a),!!c,v,d>>2,16*b)},lf=a=>{a=M[a];L.useProgram(a);L.fj=a},mf=(a,b)=>{L.vertexAttribDivisor(a,b)},nf=(a,b,c,d,e)=>{L.vertexAttribIPointer(a,b,c,d,e)},of=(a,b,c,d,e,f)=>{L.vertexAttribPointer(a,b,c,!!d,e,f)},pf=(a,b,c,d)=>L.viewport(a,b,c,d),qf=(a,b)=>{if(!V.fullscreenEnabled())return-1;a=X(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?pd()?Fd(a,b):b.jj?(nd(Fd,1,[a,b]),1):-2:-3:-4},rf=()=>{try{if(navigator.getGamepads)return(V.ui=
navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},sf=(a,b)=>{var c={target:X(2),Ph:"beforeunload",Vh:b,Yh:(d=event)=>{var e=A(b)(28,0,a);e&&=e?x(q,e):"";if(e)return d.preventDefault(),d.returnValue=e},Uh:!0};return W(c)},tf=(a,b,c,d,e,f)=>{V.Bi||(V.Bi=y(256));a={target:X(a),Ph:f,Vh:d,Yh:(h=event)=>{var k=h.target.id?h.target.id:"",m=V.Bi;z(rd(h.target),m+0,128);z(k,m+128,128);A(d)(e,m,b)&&h.preventDefault()},Uh:c};return W(a)},uf=(a,b,c,d,e)=>{V.Ci||(V.Ci=y(276));return W({target:a,
Ph:e,Vh:d,Yh:(f=event)=>{var h=V.Ci,k=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,m=!!k;n[h]=m;n[h+1]=V.fullscreenEnabled();var p=m?k:V.wj,r=p?.id||"";z(rd(p),h+2,128);z(r,h+130,128);t[h+260>>2]=p?p.clientWidth:0;t[h+264>>2]=p?p.clientHeight:0;t[h+268>>2]=screen.width;t[h+272>>2]=screen.height;m&&(V.wj=k);A(d)(19,h,b)&&f.preventDefault()},Uh:c})},vf=(a,b,c,d,e)=>{V.Di||(V.Di=y(1240));b={target:X(2),pi:!0,Ph:e,Vh:c,Yh:(f=
event)=>{var h=V.Di;Hd(h,f.gamepad);A(c)(d,h,a)&&f.preventDefault()},Uh:b};return W(b)},wf=(a,b,c,d,e,f)=>{V.Gi||(V.Gi=y(160));a={target:X(a),Ph:f,Vh:d,Yh:h=>{var k=V.Gi;w[k>>3]=h.timeStamp;var m=k>>2;t[m+2]=h.location;n[k+12]=h.ctrlKey;n[k+13]=h.shiftKey;n[k+14]=h.altKey;n[k+15]=h.metaKey;n[k+16]=h.repeat;t[m+5]=h.charCode;t[m+6]=h.keyCode;t[m+7]=h.which;z(h.key||"",k+32,32);z(h.code||"",k+64,32);z(h.char||"",k+96,32);z(h.locale||"",k+128,32);A(d)(e,k,b)&&h.preventDefault()},Uh:c};return W(a)},xf=
(a,b,c)=>{w[a>>3]=b.timeStamp;var d=a>>2;t[d+2]=b.screenX;t[d+3]=b.screenY;t[d+4]=b.clientX;t[d+5]=b.clientY;n[a+24]=b.ctrlKey;n[a+25]=b.shiftKey;n[a+26]=b.altKey;n[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;t[d+8]=b.movementX;t[d+9]=b.movementY;a=Ed(c);t[d+10]=b.clientX-(a.left|0);t[d+11]=b.clientY-(a.top|0)},yf=(a,b,c,d,e,f)=>{V.yi||(V.yi=y(64));a=X(a);return W({target:a,pi:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Ph:f,Vh:d,Yh:(h=event)=>{xf(V.yi,h,a);A(d)(e,V.yi,b)&&h.preventDefault()},
Uh:c})},zf=(a,b,c,d,e)=>{V.Hi||(V.Hi=y(257));return W({target:a,Ph:e,Vh:d,Yh:(f=event)=>{var h=V.Hi,k=document.pointerLockElement||document.oi||document.bj||document.aj;n[h]=!!k;var m=k?.id||"";z(rd(k),h+1,128);z(m,h+129,128);A(d)(20,h,b)&&f.preventDefault()},Uh:c})},Af=(a,b,c,d)=>{V.Li||(V.Li=y(36));a=X(a);return W({target:a,Ph:"resize",Vh:d,Yh:(e=event)=>{if(e.target==a){var f=document.body;if(f){var h=V.Li;t[h>>2]=0;t[h+4>>2]=f.clientWidth;t[h+8>>2]=f.clientHeight;t[h+12>>2]=innerWidth;t[h+16>>
2]=innerHeight;t[h+20>>2]=outerWidth;t[h+24>>2]=outerHeight;t[h+28>>2]=pageXOffset|0;t[h+32>>2]=pageYOffset|0;A(d)(10,h,b)&&e.preventDefault()}}},Uh:c})},Bf=(a,b,c,d,e,f)=>{V.Ki||(V.Ki=y(1552));a=X(a);return W({target:a,pi:"touchstart"==f||"touchend"==f,Ph:f,Vh:d,Yh:h=>{var k={},m=h.touches;for(var p of m)p.Ui=p.Wi=0,k[p.identifier]=p;for(var r of h.changedTouches)r.Ui=1,k[r.identifier]=r;for(var C of h.targetTouches)k[C.identifier].Wi=1;m=V.Ki;w[m>>3]=h.timeStamp;n[m+12]=h.ctrlKey;n[m+13]=h.shiftKey;
n[m+14]=h.altKey;n[m+15]=h.metaKey;p=m+16;r=Ed(a);C=0;for(let B of Object.values(k))if(k=p>>2,t[k]=B.identifier,t[k+1]=B.screenX,t[k+2]=B.screenY,t[k+3]=B.clientX,t[k+4]=B.clientY,t[k+5]=B.pageX,t[k+6]=B.pageY,n[p+28]=B.Ui,n[p+29]=B.Wi,t[k+8]=B.clientX-(r.left|0),t[k+9]=B.clientY-(r.top|0),p+=48,31<++C)break;t[m+8>>2]=C;A(d)(e,m,b)&&h.preventDefault()},Uh:c})},Cf=(a,b,c)=>{var d=td[1];V.Ni||(V.Ni=y(8));return W({target:d,Ph:"visibilitychange",Vh:c,Yh:(e=event)=>{var f=V.Ni,h=["hidden","visible","prerender",
"unloaded"].indexOf(document.visibilityState);n[f]=document.hidden;t[f+4>>2]=h;A(c)(21,f,a)&&e.preventDefault()},Uh:b})},Df=(a,b,c,d)=>{V.Oi||(V.Oi=y(96));return W({target:a,pi:!0,Ph:"wheel",Vh:d,Yh:(e=event)=>{var f=V.Oi;xf(f,e,a);w[f+64>>3]=e.deltaX;w[f+72>>3]=e.deltaY;w[f+80>>3]=e.deltaZ;t[f+88>>2]=e.deltaMode;A(d)(9,f,b)&&e.preventDefault()},Uh:c})},Ef={},Gf=()=>{if(!Ff){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&
navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Ef)void 0===Ef[b]?delete a[b]:a[b]=Ef[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ff=c}return Ff},Ff,Hf=[null,[],[]],If=Array(256),Jf=0;256>Jf;++Jf)If[Jf]=String.fromCharCode(Jf);Qa=If;E=g.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};Va=g.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};
Object.assign(hb.prototype,{isAliasOf:function(a){if(!(this instanceof hb&&a instanceof hb))return!1;var b=this.Lh.Oh.Mh,c=this.Lh.Nh;a.Lh=a.Lh;var d=a.Lh.Oh.Mh;for(a=a.Lh.Nh;b.Sh;)c=b.ni(c),b=b.Sh;for(;d.Sh;)a=d.ni(a),d=d.Sh;return b===d&&c===a},clone:function(){this.Lh.Nh||Ya(this);if(this.Lh.li)return this.Lh.count.value+=1,this;var a=eb,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Lh;a=a(c.call(b,d,{Lh:{value:{count:e.count,ki:e.ki,li:e.li,Nh:e.Nh,Oh:e.Oh,Rh:e.Rh,Th:e.Th}}}));a.Lh.count.value+=
1;a.Lh.ki=!1;return a},["delete"](){this.Lh.Nh||Ya(this);if(this.Lh.ki&&!this.Lh.li)throw new E("Object already scheduled for deletion");$a(this);var a=this.Lh;--a.count.value;0===a.count.value&&(a.Rh?a.Th.fi(a.Rh):a.Oh.Mh.fi(a.Nh));this.Lh.li||(this.Lh.Rh=void 0,this.Lh.Nh=void 0)},isDeleted:function(){return!this.Lh.Nh},deleteLater:function(){this.Lh.Nh||Ya(this);if(this.Lh.ki&&!this.Lh.li)throw new E("Object already scheduled for deletion");gb.push(this);this.Lh.ki=!0;return this}});
Object.assign(ub.prototype,{qj(a){this.Yi&&(a=this.Yi(a));return a},Si(a){this.fi?.(a)},ci:8,readValueFromPointer:tb,fromWireType:function(a){function b(){return this.ti?fb(this.Mh.hi,{Oh:this.vj,Nh:c,Th:this,Rh:a}):fb(this.Mh.hi,{Oh:this,Nh:a})}var c=this.qj(a);if(!c)return this.Si(a),null;var d=db(this.Mh,c);if(void 0!==d){if(0===d.Lh.count.value)return d.Lh.Nh=c,d.Lh.Rh=a,d.clone();d=d.clone();this.Si(a);return d}d=this.Mh.pj(c);d=bb[d];if(!d)return b.call(this);d=this.si?d.cj:d.pointerType;var e=
ab(c,this.Mh,d.Mh);return null===e?b.call(this):this.ti?fb(d.Mh.hi,{Oh:d,Nh:e,Th:this,Rh:a}):fb(d.Mh.hi,{Oh:d,Nh:e})}});zb=g.UnboundTypeError=((a,b)=>{var c=ib(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
Kb.push(0,1,void 0,1,null,1,!0,1,!1,1);g.count_emval_handles=()=>Kb.length/2-5-Jb.length;
g.requestFullscreen=function(a,b){function c(){cc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=kc,ic&&d.requestPointerLock(),cc=!0,jc?("undefined"!=typeof SDL&&(t[SDL.screen>>2]=u[SDL.screen>>2]|8388608),nc(g.canvas),mc()):nc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),jc?("undefined"!=typeof SDL&&(t[SDL.screen>>2]=
u[SDL.screen>>2]&-8388609),nc(g.canvas),mc()):nc(d));g.onFullScreen?.(cc);g.onFullscreen?.(cc)}ic=a;jc=b;"undefined"==typeof ic&&(ic=!0);"undefined"==typeof jc&&(jc=!1);var d=g.canvas;hc||(hc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};g.setCanvasSize=function(a,b,c){nc(g.canvas,a,b);c||mc()};g.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
g.createContext=function(a,b,c,d){if(b&&g.Zh&&a==g.canvas)return g.Zh;var e;if(b){var f={antialias:!1,alpha:!1,Vi:2};if(d)for(var h in d)f[h]=d[h];if("undefined"!=typeof Nc&&(e=Kc(a,f)))var k=O[e].bi}else k=a.getContext("2d");if(!k)return null;c&&(g.Zh=k,b&&Mc(e),ec.forEach(m=>m()),fc());return k};g.requestAnimationFrame=hd;g.pauseMainLoop=fd;g.resumeMainLoop=function(){Pc++;var a=Yc,b=Zc,c=Qc;Qc=null;ed(c,0,!1,Rc,!0);dd(a,b);$c()};g.preMainLoop&&bd.push(g.preMainLoop);g.postMainLoop&&cd.push(g.postMainLoop);
for(var Kf=0;32>Kf;++Kf)oe.push(Array(Kf));
var Pf={eh:function(a){(a=a?a?x(q,a):"":null)&&window.open(a,"_blank")},nb:(a,b)=>A(a)(b),R:function(){return 0},wb:()=>{},yb:function(){return 0},ub:()=>{},Ia:function(){},vb:()=>{},Db:()=>{za("")},mb:()=>{},cb:(a,b,c,d)=>{b=D(b);F(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},ci:8,readValueFromPointer:function(e){return this.fromWireType(q[e])},ai:null})},dg:(a,b,c,d,e,f,h,k,m,p,r,C,B)=>{r=D(r);f=yb(e,f);k&&=yb(h,k);p&&=yb(m,p);B=yb(C,B);var K=lb(r);kb(K,function(){Cb(`Cannot construct ${r} due to unbound types`,
[d])});Wa([a,b,c],d?[d]:[],H=>{H=H[0];if(d){var R=H.Mh;var na=R.hi}else na=hb.prototype;H=ib(r,function(...Pa){if(Object.getPrototypeOf(this)!==Oa)throw new E("Use 'new' to construct "+r);if(void 0===S.gi)throw new E(r+" has no accessible constructor");var We=S.gi[Pa.length];if(void 0===We)throw new E(`Tried to invoke ctor of ${r} with invalid number of parameters (${Pa.length}) - expected (${Object.keys(S.gi).toString()}) parameters instead!`);return We.apply(this,Pa)});var Oa=Object.create(na,{constructor:{value:H}});
H.prototype=Oa;var S=new mb(r,H,Oa,B,R,f,k,p);if(S.Sh){var oa;(oa=S.Sh).Pi??(oa.Pi=[]);S.Sh.Pi.push(S)}R=new ub(r,S,!0,!1,!1);oa=new ub(r+"*",S,!1,!1,!1);na=new ub(r+" const*",S,!1,!0,!1);bb[a]={pointerType:oa,cj:na};vb(K,H);return[R,oa,na]})},be:(a,b,c,d,e,f)=>{var h=Db(b,c);e=yb(d,e);Wa([],[a],k=>{k=k[0];var m=`constructor ${k.name}`;void 0===k.Mh.gi&&(k.Mh.gi=[]);if(void 0!==k.Mh.gi[b-1])throw new E(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
k.Mh.gi[b-1]=()=>{Cb(`Cannot construct ${k.name} due to unbound types`,h)};Wa([],h,p=>{p.splice(1,0,null);k.Mh.gi[b-1]=Hb(m,p,null,e,f);return[]});return[]})},C:(a,b,c,d,e,f,h,k,m)=>{var p=Db(c,d);b=D(b);b=Ib(b);f=yb(e,f);Wa([],[a],r=>{function C(){Cb(`Cannot call ${B} due to unbound types`,p)}r=r[0];var B=`${r.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&r.Mh.xj.push(b);var K=r.Mh.hi,H=K[b];void 0===H||void 0===H.Qh&&H.className!==r.name&&H.ji===c-2?(C.ji=c-2,C.className=r.name,
K[b]=C):(jb(K,b,B),K[b].Qh[c-2]=C);Wa([],p,R=>{R=Hb(B,R,r,f,h,m);void 0===K[b].Qh?(R.ji=c-2,K[b]=R):K[b].Qh[c-2]=R;return[]});return[]})},nh:a=>F(a,Lb),Sa:(a,b,c)=>{b=D(b);F(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,ci:8,readValueFromPointer:Mb(b,c),ai:null})},g:(a,b,c,d,e,f,h)=>{var k=Db(b,c);a=D(a);a=Ib(a);e=yb(d,e);kb(a,function(){Cb(`Cannot call ${a} due to unbound types`,k)},b-1);Wa([],k,m=>{vb(a,Hb(a,[m[0],null].concat(m.slice(1)),null,e,f,h),b-1);return[]})},q:(a,b,c,d,e)=>{b=D(b);-1===
e&&(e=4294967295);e=k=>k;if(0===d){var f=32-8*c;e=k=>k<<f>>>f}var h=b.includes("unsigned")?function(k,m){return m>>>0}:function(k,m){return m};F(a,{name:b,fromWireType:e,toWireType:h,ci:8,readValueFromPointer:Nb(b,c,0!==d),ai:null})},d:(a,b,c)=>{function d(f){return new e(n.buffer,u[f+4>>2],u[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=D(c);F(a,{name:c,fromWireType:d,ci:8,readValueFromPointer:d},{sj:!0})},sh:a=>{F(a,Ob)},ja:(a,b)=>
{b=D(b);var c="std::string"===b;F(a,{name:b,fromWireType:function(d){var e=u[d>>2],f=d+4;if(c)for(var h=f,k=0;k<=e;++k){var m=f+k;if(k==e||0==q[m]){h=h?x(q,h,m-h):"";if(void 0===p)var p=h;else p+=String.fromCharCode(0),p+=h;h=m+1}}else{p=Array(e);for(k=0;k<e;++k)p[k]=String.fromCharCode(q[f+k]);p=p.join("")}G(d);return p},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new E("Cannot pass non-string to std::string");
var h=c&&f?Pb(e):e.length;var k=y(4+h+1),m=k+4;u[k>>2]=h;if(c&&f)z(e,m,h+1);else if(f)for(f=0;f<h;++f){var p=e.charCodeAt(f);if(255<p)throw G(m),new E("String has UTF-16 code units that do not fit in 8 bits");q[m+f]=p}else for(f=0;f<h;++f)q[m+f]=e[f];null!==d&&d.push(G,k);return k},ci:8,readValueFromPointer:tb,ai(d){G(d)}})},ga:(a,b,c)=>{c=D(c);if(2===b){var d=Rb;var e=Sb;var f=Tb;var h=k=>qa[k>>1]}else 4===b&&(d=Ub,e=Vb,f=Wb,h=k=>u[k>>2]);F(a,{name:c,fromWireType:k=>{for(var m=u[k>>2],p,r=k+4,C=
0;C<=m;++C){var B=k+4+C*b;if(C==m||0==h(B))r=d(r,B-r),void 0===p?p=r:(p+=String.fromCharCode(0),p+=r),r=B+b}G(k);return p},toWireType:(k,m)=>{if("string"!=typeof m)throw new E(`Cannot pass non-string to C++ string type ${c}`);var p=f(m),r=y(4+p+b);u[r>>2]=p/b;e(m,r+4,p+b);null!==k&&k.push(G,r);return r},ci:8,readValueFromPointer:tb,ai(k){G(k)}})},db:(a,b)=>{b=D(b);F(a,{Oj:!0,name:b,ci:0,fromWireType:()=>{},toWireType:()=>{}})},Bb:()=>1,Cb:(a,b,c)=>q.copyWithin(a,b,b+c),pb:()=>{Ja=!1;Xb=0},sb:()=>
{throw Infinity;},ib:(a,b)=>{var c=Sa[a];if(void 0===c)throw a=`${"_emval_take_value"} has unknown type ${Bb(a)}`,new E(a);a=c;a=a.readValueFromPointer(b);return rb(a)},jb:function(){return-52},kb:function(){},qb:(a,b)=>{Yb[a]&&(clearTimeout(Yb[a].id),delete Yb[a]);if(!b)return 0;var c=setTimeout(()=>{delete Yb[a];bc(()=>Lf(a,performance.now()))},b);Yb[a]={id:c,Vj:b};return 0},rb:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();
u[a>>2]=60*Math.max(f,e);t[b>>2]=Number(f!=e);b=h=>{var k=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(z(a,c,17),z(b,d,17)):(z(a,d,17),z(b,c,17))},$c:a=>{if(12448==a)return I=12288,1;I=12300;return 0},of:(a,b,c,d,e)=>{if(62E3!=a)I=12296,c=0;else{if(b)for(;;){a=t[b>>2];if(12321==a)J.alpha=0<t[b+4>>2];else if(12325==a)J.depth=0<t[b+4>>2];else if(12326==a)J.stencil=0<t[b+4>>2];else if(12337==a)a=t[b+4>>2],J.antialias=
0<a;else if(12338==a)a=t[b+4>>2],J.antialias=1==a;else if(12544==a)J.Pj=12547!=t[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(t[e>>2]=1),c&&0<d&&(u[c>>2]=62002),I=12288,c=1):(I=12300,c=0)}return c},Te:(a,b,c,d)=>{if(62E3!=a)return I=12296,0;for(a=1;;){b=t[d>>2];if(12440==b)a=t[d+4>>2];else if(12344==b)break;else return I=12292,0;d+=8}if(2>a||3<a)return I=12293,0;J.Vi=a-1;J.Rj=0;tc=Kc(g.canvas,J);if(0!=tc)return I=12288,Mc(tc),ec.forEach(e=>e()),Mc(null),62004;I=12297;return 0},xe:(a,b)=>{if(62E3!=
a)return I=12296,0;if(62002!=b)return I=12293,0;I=12288;return 62006},Ie:(a,b)=>{if(62E3!=a)return I=12296,0;if(62004!=b)return I=12294,0;a=tc;U===O[a]&&(U=null);"object"==typeof V&&V.Aj(O[a].bi.canvas);O[a]&&O[a].bi.canvas&&(O[a].bi.canvas.ii=void 0);O[a]=null;I=12288;pc==b&&(pc=0);return 1},me:(a,b)=>{if(62E3!=a)return I=12296,0;if(62006!=b)return I=12301,1;qc==b&&(qc=0);rc==b&&(rc=0);I=12288;return 1},cf:(a,b,c,d)=>{if(62E3!=a)return I=12296,0;if(62002!=b)return I=12293,0;if(!d)return I=12300,
0;I=12288;switch(c){case 12320:return t[d>>2]=J.alpha?32:24,1;case 12321:return t[d>>2]=J.alpha?8:0,1;case 12322:return t[d>>2]=8,1;case 12323:return t[d>>2]=8,1;case 12324:return t[d>>2]=8,1;case 12325:return t[d>>2]=J.depth?24:0,1;case 12326:return t[d>>2]=J.stencil?8:0,1;case 12327:return t[d>>2]=12344,1;case 12328:return t[d>>2]=62002,1;case 12329:return t[d>>2]=0,1;case 12330:return t[d>>2]=4096,1;case 12331:return t[d>>2]=16777216,1;case 12332:return t[d>>2]=4096,1;case 12333:return t[d>>2]=
0,1;case 12334:return t[d>>2]=0,1;case 12335:return t[d>>2]=12344,1;case 12337:return t[d>>2]=J.antialias?4:0,1;case 12338:return t[d>>2]=J.antialias?1:0,1;case 12339:return t[d>>2]=4,1;case 12340:return t[d>>2]=12344,1;case 12341:case 12342:case 12343:return t[d>>2]=-1,1;case 12345:case 12346:return t[d>>2]=0,1;case 12347:return t[d>>2]=0,1;case 12348:return t[d>>2]=1;case 12349:case 12350:return t[d>>2]=0,1;case 12351:return t[d>>2]=12430,1;case 12352:return t[d>>2]=4,1;case 12354:return t[d>>2]=
0,1;default:return I=12292,0}},La:a=>{I=12288;return 0!=a&&1!=a?0:62E3},Fc:()=>I,Kf:(a,b,c)=>{if(62E3!=a)return I=12296,0;b&&(t[b>>2]=1);c&&(t[c>>2]=4);oc=!0;I=12288;return 1},ae:(a,b,c,d)=>{if(62E3!=a)return I=12296,0;if(0!=d&&62004!=d)return I=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return I=12301,0;Mc(d?tc:null);pc=d;rc=b;qc=c;I=12288;return 1},Qc:(a,b)=>{if(62E3!=a)return I=12296,0;I=12288;if(sc[b])return sc[b];switch(b){case 12371:a=Oc("Emscripten");break;case 12372:a=Oc("1.4 Emscripten EGL");
break;case 12373:a=Oc("");break;case 12429:a=Oc("OpenGL_ES");break;default:return I=12300,0}return sc[b]=a},Rd:()=>{if(oc)if(g.Zh)if(g.Zh.isContextLost())I=12302;else return I=12288,1;else I=12290;else I=12289;return 0},Gd:(a,b)=>{if(62E3!=a)return I=12296,0;0==b?dd(0,0):dd(1,b);I=12288;return 1},zf:a=>{if(62E3!=a)return I=12296,0;rc=qc=pc=0;oc=!1;I=12288;return 1},kd:()=>{I=12288;return 1},vd:()=>{I=12288;return 1},$a:(a,b,c)=>{b=ld(b,c);return Ga[a](...b)},D:(a,b,c)=>{b=ld(b,c);return Ga[a](...b)},
og:(a,b,c)=>{b=ld(b,c);return Ga[a](...b)},Ma:()=>{fd();Qc=null},Ja:()=>Date.now(),fb:()=>{if(!V.fullscreenEnabled())return-1;od(Fd);var a=td[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},$b:()=>{od(Gd);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},la:ud,B:()=>devicePixelRatio,w:(a,b,c)=>{a=X(a);if(!a)return-4;a=Ed(a);w[b>>3]=a.width;w[c>>3]=
a.height;return 0},ma:(a,b)=>{if(0>a||a>=V.ui.length)return-5;if(!V.ui[a])return-7;Hd(b,V.ui[a]);return 0},M:()=>performance.now(),eb:()=>V.ui.length,uc:(a,b)=>{t[a>>2]=screen.width;t[b>>2]=screen.height},Kg:Id,Jg:Jd,td:(a,b)=>{L.beginQuery(a,P[b])},_g:(a,b)=>{L.Wh.beginQueryEXT(a,P[b])},_c:a=>L.beginTransformFeedback(a),Ig:(a,b,c)=>{L.bindAttribLocation(M[a],b,c?x(q,c):"")},Hg:Kd,Xc:Ld,Yc:Md,Gg:Nd,Fg:(a,b)=>{L.bindRenderbuffer(a,yc[b])},ac:(a,b)=>{L.bindSampler(a,Q[b])},Eg:Od,Tb:(a,b)=>{L.bindTransformFeedback(a,
Bc[b])},ed:Pd,Sg:Pd,Dg:(a,b,c,d)=>L.blendColor(a,b,c,d),Cg:Qd,Bg:Rd,Ag:(a,b)=>L.blendFunc(a,b),zg:Sd,hd:(a,b,c,d,e,f,h,k,m,p)=>L.blitFramebuffer(a,b,c,d,e,f,h,k,m,p),yg:Td,xg:Ud,wg:Vd,vg:Wd,yc:(a,b,c,d)=>L.clearBufferfi(a,b,c,d),zc:Xd,Bc:(a,b,c)=>{L.clearBufferiv(a,b,t,c>>2)},Ac:Yd,ug:Zd,tg:a=>L.clearDepth(a),sg:a=>L.clearStencil(a),jc:(a,b,c,d)=>L.clientWaitSync(Cc[a],b,(c>>>0)+4294967296*d),Pd:(a,b)=>{L.mj.clipControlEXT(a,b)},rg:(a,b,c,d)=>{L.colorMask(!!a,!!b,!!c,!!d)},qg:$d,pg:(a,b,c,d,e,f,h,
k)=>{L.$h||!h?L.compressedTexImage2D(a,b,c,d,e,f,h,k):L.compressedTexImage2D(a,b,c,d,e,f,q,k,h)},zd:(a,b,c,d,e,f,h,k,m)=>{L.$h?L.compressedTexImage3D(a,b,c,d,e,f,h,k,m):L.compressedTexImage3D(a,b,c,d,e,f,h,q,m,k)},ng:(a,b,c,d,e,f,h,k,m)=>{L.$h||!k?L.compressedTexSubImage2D(a,b,c,d,e,f,h,k,m):L.compressedTexSubImage2D(a,b,c,d,e,f,h,q,m,k)},yd:(a,b,c,d,e,f,h,k,m,p,r)=>{L.$h?L.compressedTexSubImage3D(a,b,c,d,e,f,h,k,m,p,r):L.compressedTexSubImage3D(a,b,c,d,e,f,h,k,m,q,r,p)},wc:(a,b,c,d,e)=>L.copyBufferSubData(a,
b,c,d,e),mg:(a,b,c,d,e,f,h,k)=>L.copyTexImage2D(a,b,c,d,e,f,h,k),lg:(a,b,c,d,e,f,h,k)=>L.copyTexSubImage2D(a,b,c,d,e,f,h,k),Ad:(a,b,c,d,e,f,h,k,m)=>L.copyTexSubImage3D(a,b,c,d,e,f,h,k,m),kg:ae,jg:be,ig:ce,hg:de,gg:ee,fg:fe,wd:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=P[d];e&&(L.deleteQuery(e),P[d]=null)}},ah:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=P[d];e&&(L.Wh.deleteQueryEXT(e),P[d]=null)}},eg:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=yc[d];e&&(L.deleteRenderbuffer(e),e.name=
0,yc[d]=null)}},cc:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Q[d];e&&(L.deleteSampler(e),e.name=0,Q[d]=null)}},cg:ge,kc:a=>{if(a){var b=Cc[a];b?(L.deleteSync(b),b.name=0,Cc[a]=null):T||=1281}},bg:he,Sb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Bc[d];e&&(L.deleteTransformFeedback(e),e.name=0,Bc[d]=null)}},dd:ie,Rg:ie,ag:je,$f:a=>{L.depthMask(!!a)},_f:(a,b)=>L.depthRange(a,b),Zf:ke,Yf:le,Xf:a=>{L.disableVertexAttribArray(a)},Wf:me,oc:ne,Ng:ne,Kd:ne,Ld:ne,Eb:ne,pd:pe,Fd:pe,Og:pe,Vf:qe,
nc:re,Mg:re,Hd:re,Id:re,Jd:re,Dd:(a,b,c,d,e,f)=>{L.drawElements(a,d,e,f)},Uf:se,Tf:te,sd:a=>L.endQuery(a),Zg:a=>{L.Wh.endQueryEXT(a)},Zc:()=>L.endTransformFeedback(),mc:(a,b)=>(a=L.fenceSync(a,b))?(b=Hc(Cc),a.name=b,Cc[b]=a,b):0,Sf:()=>L.finish(),Rf:()=>L.flush(),Qf:(a,b,c,d)=>{L.framebufferRenderbuffer(a,b,c,yc[d])},Pf:ue,fd:ve,Of:a=>L.frontFace(a),Nf:we,Lf:xe,xd:(a,b)=>{Ic(a,b,"createQuery",P)},bh:(a,b)=>{for(var c=0;c<a;c++){var d=L.Wh.createQueryEXT();if(!d){for(T||=1282;c<a;)t[b+4*c++>>2]=0;
break}var e=Hc(P);d.name=e;P[e]=d;t[b+4*c>>2]=e}},Jf:(a,b)=>{Ic(a,b,"createRenderbuffer",yc)},dc:(a,b)=>{Ic(a,b,"createSampler",Q)},If:ye,Rb:(a,b)=>{Ic(a,b,"createTransformFeedback",Bc)},cd:ze,Qg:ze,Mf:a=>L.generateMipmap(a),Hf:(a,b,c,d,e,f,h)=>{Ae("getActiveAttrib",a,b,c,d,e,f,h)},Gf:(a,b,c,d,e,f,h)=>{Ae("getActiveUniform",a,b,c,d,e,f,h)},qc:(a,b,c,d,e)=>{a=M[a];if(a=L.getActiveUniformBlockName(a,b))e&&0<c?(c=z(a,e,c),d&&(t[d>>2]=c)):d&&(t[d>>2]=0)},rc:(a,b,c,d)=>{if(d)if(a=M[a],35393==c)t[d>>2]=
L.getActiveUniformBlockName(a,b).length+1;else{if(a=L.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)t[d+4*c>>2]=a[c];else t[d>>2]=a}else T||=1281},tc:(a,b,c,d,e)=>{if(e)if(0<b&&0==c)T||=1281;else{a=M[a];for(var f=[],h=0;h<b;h++)f.push(t[c+4*h>>2]);if(a=L.getActiveUniforms(a,f,d))for(b=a.length,h=0;h<b;h++)t[e+4*h>>2]=a[h]}else T||=1281},Ff:(a,b,c,d)=>{a=L.getAttachedShaders(M[a]);var e=a.length;e>b&&(e=b);t[c>>2]=e;for(b=0;b<e;++b)t[d+4*b>>2]=N.indexOf(a[b])},Ef:Be,
Df:(a,b)=>Ee(a,b,4),ec:(a,b,c)=>{c?Ce(c,L.getBufferParameter(a,b)):T||=1281},Cf:(a,b,c)=>{c?t[c>>2]=L.getBufferParameter(a,b):T||=1281},Bf:()=>{var a=L.getError()||T;T=0;return a},Af:(a,b)=>Ee(a,b,2),Lc:(a,b)=>L.getFragDataLocation(M[a],b?x(q,b):""),yf:(a,b,c,d)=>{a=L.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;t[d>>2]=a},fc:(a,b,c)=>Fe(a,b,c,1),hc:(a,b)=>{Ee(a,b,1)},ad:(a,b,c)=>Fe(a,b,c,0),xf:Ge,Gb:(a,b,c,d,e)=>{if(0>d)T||=1281;
else if(e){if(a=L.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)t[e+4*b>>2]=a[b]}else T||=1281},Nb:()=>{T||=1282},vf:He,wf:Ie,Ug:Je,Wg:Ke,Tg:Je,qd:(a,b,c)=>{if(c){a=L.getQueryParameter(P[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d}else T||=1281},Vg:Ke,rd:(a,b,c)=>{c?t[c>>2]=L.getQuery(a,b):T||=1281},Xg:(a,b,c)=>{c?t[c>>2]=L.Wh.getQueryEXT(a,b):T||=1281},uf:(a,b,c)=>{c?t[c>>2]=L.getRenderbufferParameter(a,b):T||=1281},Vb:(a,b,c)=>{c?v[c>>2]=L.getSamplerParameter(Q[a],
b):T||=1281},Wb:(a,b,c)=>{c?t[c>>2]=L.getSamplerParameter(Q[a],b):T||=1281},sf:Le,rf:(a,b,c,d)=>{a=L.getShaderPrecisionFormat(a,b);t[c>>2]=a.rangeMin;t[c+4>>2]=a.rangeMax;t[d>>2]=a.precision},qf:(a,b,c,d)=>{if(a=L.getShaderSource(N[a]))b=0<b&&d?z(a,d,b):0,c&&(t[c>>2]=b)},tf:Me,pf:a=>{var b=Dc[a];if(!b){switch(a){case 7939:b=Oc(De().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=L.getParameter(a))||(T||=1280);b=b?Oc(b):0;break;case 7938:b=Oc(`OpenGL ES 3.0 (${L.getParameter(7938)})`);
break;case 35724:b=L.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Oc(b);break;default:T||=1280}Dc[a]=b}return b},xc:(a,b)=>{if(2>U.version)return T||=1282,0;var c=Ec[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=De().map(Oc),c=Ec[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},gc:(a,b,c,d,e)=>{0>c?T||=1281:e?(a=L.getSyncParameter(Cc[a],
b),null!==a&&(t[e>>2]=a,d&&(t[d>>2]=1))):T||=1281},nf:(a,b,c)=>{c?v[c>>2]=L.getTexParameter(a,b):T||=1281},mf:(a,b,c)=>{c?t[c>>2]=L.getTexParameter(a,b):T||=1281},Vc:(a,b,c,d,e,f,h)=>{a=M[a];if(a=L.getTransformFeedbackVarying(a,b))h&&0<c?(c=z(a.name,h,c),d&&(t[d>>2]=c)):d&&(t[d>>2]=0),e&&(t[e>>2]=a.size),f&&(t[f>>2]=a.type)},sc:Ne,vc:(a,b,c,d)=>{if(d)if(0<b&&(0==c||0==d))T||=1281;else{a=M[a];for(var e=[],f=0;f<b;f++)e.push(Na(t[c+4*f>>2]));if(a=L.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)t[d+
4*f>>2]=a[f]}else T||=1281},jf:Qe,lf:(a,b,c)=>{Re(a,b,c,2)},kf:(a,b,c)=>{Re(a,b,c,0)},Mc:(a,b,c)=>Re(a,b,c,0),Tc:Te,Sc:Te,ff:(a,b,c)=>{c?t[c>>2]=L.getVertexAttribOffset(a,b):T||=1281},hf:(a,b,c)=>{Se(a,b,c,2)},gf:(a,b,c)=>{Se(a,b,c,5)},ef:(a,b)=>L.hint(a,b),Kb:(a,b,c)=>{for(var d=oe[b],e=0;e<b;e++)d[e]=t[c+4*e>>2];L.invalidateFramebuffer(a,d)},Jb:(a,b,c,d,e,f,h)=>{for(var k=oe[b],m=0;m<b;m++)k[m]=t[c+4*m>>2];L.invalidateSubFramebuffer(a,k,d,e,f,h)},df:a=>(a=wc[a])?L.isBuffer(a):0,bf:Ue,af:a=>(a=xc[a])?
L.isFramebuffer(a):0,$e:Ve,ud:a=>(a=P[a])?L.isQuery(a):0,$g:a=>(a=P[a])?L.Wh.isQueryEXT(a):0,_e:a=>(a=yc[a])?L.isRenderbuffer(a):0,bc:a=>(a=Q[a])?L.isSampler(a):0,Ze:a=>(a=N[a])?L.isShader(a):0,lc:a=>L.isSync(Cc[a]),Ye:a=>(a=zc[a])?L.isTexture(a):0,Qb:a=>L.isTransformFeedback(Bc[a]),bd:Xe,Pg:Xe,Xe:a=>L.lineWidth(a),We:Ye,Pb:()=>L.pauseTransformFeedback(),Ve:Ze,Od:(a,b)=>{L.Dj.polygonModeWEBGL(a,b)},Ue:(a,b)=>L.polygonOffset(a,b),Qd:(a,b,c)=>{L.nj.polygonOffsetClampEXT(a,b,c)},Mb:()=>{T||=1280},Lb:()=>
{T||=1280},Yg:(a,b)=>{L.Wh.queryCounterEXT(P[a],b)},Ed:$e,Se:(a,b,c,d,e,f,h)=>{if(L.Ai)L.readPixels(a,b,c,d,e,f,h);else{var k=af(f);h>>>=31-Math.clz32(k.BYTES_PER_ELEMENT);L.readPixels(a,b,c,d,e,f,k,h)}},Re:()=>{},Qe:(a,b,c,d)=>L.renderbufferStorage(a,b,c,d),gd:(a,b,c,d,e)=>L.renderbufferStorageMultisample(a,b,c,d,e),Ob:()=>L.resumeTransformFeedback(),Pe:(a,b)=>{L.sampleCoverage(a,!!b)},Yb:(a,b,c)=>{L.samplerParameterf(Q[a],b,c)},Xb:(a,b,c)=>{L.samplerParameterf(Q[a],b,v[c>>2])},_b:(a,b,c)=>{L.samplerParameteri(Q[a],
b,c)},Zb:(a,b,c)=>{L.samplerParameteri(Q[a],b,t[c>>2])},Oe:cf,Ne:()=>{T||=1280},Me:df,Le:(a,b,c)=>L.stencilFunc(a,b,c),Ke:(a,b,c,d)=>L.stencilFuncSeparate(a,b,c,d),Je:a=>L.stencilMask(a),He:(a,b)=>L.stencilMaskSeparate(a,b),Ge:(a,b,c)=>L.stencilOp(a,b,c),Fe:(a,b,c,d)=>L.stencilOpSeparate(a,b,c,d),Ee:ef,Cd:ff,De:(a,b,c)=>L.texParameterf(a,b,c),Ce:(a,b,c)=>{L.texParameterf(a,b,v[c>>2])},Be:gf,Ae:(a,b,c)=>{L.texParameteri(a,b,t[c>>2])},Ib:(a,b,c,d,e)=>L.texStorage2D(a,b,c,d,e),Hb:(a,b,c,d,e,f)=>L.texStorage3D(a,
b,c,d,e,f),ze:(a,b,c,d,e,f,h,k,m)=>{if(L.$h)L.texSubImage2D(a,b,c,d,e,f,h,k,m);else if(m){var p=af(k);L.texSubImage2D(a,b,c,d,e,f,h,k,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else m=m?bf(k,h,e,f,m):null,L.texSubImage2D(a,b,c,d,e,f,h,k,m)},Bd:(a,b,c,d,e,f,h,k,m,p,r)=>{if(L.$h)L.texSubImage3D(a,b,c,d,e,f,h,k,m,p,r);else if(r){var C=af(p);L.texSubImage3D(a,b,c,d,e,f,h,k,m,p,C,r>>>31-Math.clz32(C.BYTES_PER_ELEMENT))}else L.texSubImage3D(a,b,c,d,e,f,h,k,m,p,null)},Wc:(a,b,c,d)=>{a=M[a];for(var e=[],f=
0;f<b;f++)e.push(Na(t[c+4*f>>2]));L.transformFeedbackVaryings(a,e,d)},ye:(a,b)=>{L.uniform1f(Y(a),b)},we:(a,b,c)=>{b&&L.uniform1fv(Y(a),v,c>>2,b)},ve:hf,ue:(a,b,c)=>{b&&L.uniform1iv(Y(a),t,c>>2,b)},Kc:(a,b)=>{L.uniform1ui(Y(a),b)},Gc:(a,b,c)=>{b&&L.uniform1uiv(Y(a),u,c>>2,b)},te:(a,b,c)=>{L.uniform2f(Y(a),b,c)},se:(a,b,c)=>{b&&L.uniform2fv(Y(a),v,c>>2,2*b)},re:(a,b,c)=>{L.uniform2i(Y(a),b,c)},qe:(a,b,c)=>{b&&L.uniform2iv(Y(a),t,c>>2,2*b)},Jc:(a,b,c)=>{L.uniform2ui(Y(a),b,c)},Ec:(a,b,c)=>{b&&L.uniform2uiv(Y(a),
u,c>>2,2*b)},pe:(a,b,c,d)=>{L.uniform3f(Y(a),b,c,d)},oe:(a,b,c)=>{b&&L.uniform3fv(Y(a),v,c>>2,3*b)},ne:(a,b,c,d)=>{L.uniform3i(Y(a),b,c,d)},le:(a,b,c)=>{b&&L.uniform3iv(Y(a),t,c>>2,3*b)},Ic:(a,b,c,d)=>{L.uniform3ui(Y(a),b,c,d)},Dc:(a,b,c)=>{b&&L.uniform3uiv(Y(a),u,c>>2,3*b)},ke:(a,b,c,d,e)=>{L.uniform4f(Y(a),b,c,d,e)},je:(a,b,c)=>{b&&L.uniform4fv(Y(a),v,c>>2,4*b)},ie:(a,b,c,d,e)=>{L.uniform4i(Y(a),b,c,d,e)},he:(a,b,c)=>{b&&L.uniform4iv(Y(a),t,c>>2,4*b)},Hc:(a,b,c,d,e)=>{L.uniform4ui(Y(a),b,c,d,e)},
Cc:(a,b,c)=>{b&&L.uniform4uiv(Y(a),u,c>>2,4*b)},pc:jf,ge:(a,b,c,d)=>{b&&L.uniformMatrix2fv(Y(a),!!c,v,d>>2,4*b)},od:(a,b,c,d)=>{b&&L.uniformMatrix2x3fv(Y(a),!!c,v,d>>2,6*b)},md:(a,b,c,d)=>{b&&L.uniformMatrix2x4fv(Y(a),!!c,v,d>>2,8*b)},fe:(a,b,c,d)=>{b&&L.uniformMatrix3fv(Y(a),!!c,v,d>>2,9*b)},nd:(a,b,c,d)=>{b&&L.uniformMatrix3x2fv(Y(a),!!c,v,d>>2,6*b)},jd:(a,b,c,d)=>{b&&L.uniformMatrix3x4fv(Y(a),!!c,v,d>>2,12*b)},ee:kf,ld:(a,b,c,d)=>{b&&L.uniformMatrix4x2fv(Y(a),!!c,v,d>>2,8*b)},id:(a,b,c,d)=>{b&&
L.uniformMatrix4x3fv(Y(a),!!c,v,d>>2,12*b)},de:lf,ce:a=>{L.validateProgram(M[a])},$d:(a,b)=>L.vertexAttrib1f(a,b),_d:(a,b)=>{L.vertexAttrib1f(a,v[b>>2])},Zd:(a,b,c)=>L.vertexAttrib2f(a,b,c),Yd:(a,b)=>{L.vertexAttrib2f(a,v[b>>2],v[b+4>>2])},Xd:(a,b,c,d)=>L.vertexAttrib3f(a,b,c,d),Wd:(a,b)=>{L.vertexAttrib3f(a,v[b>>2],v[b+4>>2],v[b+8>>2])},Vd:(a,b,c,d,e)=>L.vertexAttrib4f(a,b,c,d,e),Ud:(a,b)=>{L.vertexAttrib4f(a,v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},Ub:mf,Lg:mf,Md:mf,Nd:mf,Fb:mf,Rc:(a,b,c,d,e)=>
L.vertexAttribI4i(a,b,c,d,e),Oc:(a,b)=>{L.vertexAttribI4i(a,t[b>>2],t[b+4>>2],t[b+8>>2],t[b+12>>2])},Pc:(a,b,c,d,e)=>L.vertexAttribI4ui(a,b,c,d,e),Nc:(a,b)=>{L.vertexAttribI4ui(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Uc:nf,Td:of,Sd:pf,ic:(a,b,c,d)=>{L.waitSync(Cc[a],b,(c>>>0)+4294967296*d)},U:()=>0,gb:(a,b,c)=>qf(a,{Ii:t[c>>2],zi:t[c+4>>2],oj:t[c+8>>2],jj:b,ri:t[c+12>>2],Ri:t[c+16>>2]}),Ka:(a,b)=>{a=X(a);return a?a.requestPointerLock?pd()?Gd(a):b?(nd(Gd,2,[a]),1):-2:-1:-4},tb:a=>{var b=q.length;
a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ka.buffer.byteLength+65535)/65536|0;try{ka.grow(d);ra();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},na:rf,oa:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:sf(a,b),za:(a,b,c,d)=>tf(a,b,c,d,12,"blur"),A:Ad,Q:(a,b,c)=>{a=X(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},Aa:(a,b,c,d)=>tf(a,b,c,
d,13,"focus"),qa:(a,b,c,d)=>{if(!V.fullscreenEnabled())return-1;a=X(a);if(!a)return-4;uf(a,b,c,d,"webkitfullscreenchange");return uf(a,b,c,d,"fullscreenchange")},K:(a,b,c)=>rf()?-1:vf(a,b,c,26,"gamepadconnected"),J:(a,b,c)=>rf()?-1:vf(a,b,c,27,"gamepaddisconnected"),ta:(a,b,c,d)=>wf(a,b,c,d,2,"keydown"),ra:(a,b,c,d)=>wf(a,b,c,d,1,"keypress"),sa:(a,b,c,d)=>wf(a,b,c,d,3,"keyup"),Na:(a,b,c)=>{a=A(a);ed(a,b,c)},Fa:(a,b,c,d)=>yf(a,b,c,d,5,"mousedown"),Da:(a,b,c,d)=>yf(a,b,c,d,33,"mouseenter"),Ca:(a,b,
c,d)=>yf(a,b,c,d,34,"mouseleave"),Ga:(a,b,c,d)=>yf(a,b,c,d,8,"mousemove"),Ea:(a,b,c,d)=>yf(a,b,c,d,6,"mouseup"),ua:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.oi||document.body.bj||document.body.aj))return-1;a=X(a);if(!a)return-4;zf(a,b,c,d,"mozpointerlockchange");zf(a,b,c,d,"webkitpointerlockchange");zf(a,b,c,d,"mspointerlockchange");return zf(a,b,c,d,"pointerlockchange")},L:(a,b,c,d)=>Af(a,b,c,d),va:(a,b,c,d)=>Bf(a,b,c,d,25,"touchcancel"),xa:(a,b,
c,d)=>Bf(a,b,c,d,23,"touchend"),wa:(a,b,c,d)=>Bf(a,b,c,d,24,"touchmove"),ya:(a,b,c,d)=>Bf(a,b,c,d,22,"touchstart"),pa:(a,b,c)=>Cf(a,b,c),Ba:(a,b,c,d)=>(a=X(a))?"undefined"!=typeof a.onwheel?Df(a,b,c,d):-1:-4,hb:a=>document.title=a?x(q,a):"",T:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},zb:(a,b)=>{var c=0;Gf().forEach((d,e)=>{var f=b+c;e=u[a+4*e>>2]=f;for(f=0;f<d.length;++f)n[e++]=d.charCodeAt(f);n[e]=0;c+=d.length+1});
return 0},Ab:(a,b)=>{var c=Gf();u[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);u[b>>2]=d;return 0},S:()=>52,Ha:()=>52,lb:function(){return 70},xb:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var h=u[b>>2],k=u[b+4>>2];b+=8;for(var m=0;m<k;m++){var p=a,r=q[h+m],C=Hf[p];0===r||10===r?((1===p?ha:ia)(x(C)),C.length=0):C.push(r)}e+=k}u[d>>2]=e;return 0},X:Id,$:Jd,a:Kd,F:Ld,Ya:Md,z:Nd,i:Od,n:Pd,W:Pd,gh:Qd,hh:Rd,Qa:Sd,e:Td,r:Ud,s:Vd,_a:Wd,oh:Xd,ph:Yd,qh:Zd,aa:$d,Va:ae,ca:be,fa:ce,j:de,G:ee,Z:fe,_:ge,m:he,O:ie,
jh:ie,rh:je,Pa:ke,l:le,H:me,Za:ne,ia:pe,kh:qe,h:se,f:te,v:ue,ab:ve,k:we,ka:xe,y:ye,P:ze,lh:ze,V:Be,c:Ge,Wa:He,da:Ie,Xa:Le,ea:Me,p:Ne,Y:Qe,E:Ue,ih:Ve,Ua:Ye,mh:Ze,bb:$e,Ra:cf,ba:df,t:ef,ha:ff,b:gf,Ta:hf,o:jf,fh:kf,x:lf,I:nf,u:of,N:pf,dh:Mf,Oa:Nf,ch:Of,ob:$b},Z=function(){function a(c){Z=c.exports;ka=Z.th;ra();La=Z.yh;ta.unshift(Z.uh);wa--;g.monitorRunDependencies?.(wa);0==wa&&(null!==xa&&(clearInterval(xa),xa=null),ya&&(c=ya,ya=null,c()));return Z}var b={a:Pf};wa++;g.monitorRunDependencies?.(wa);if(g.instantiateWasm)try{return g.instantiateWasm(b,
a)}catch(c){ia(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}Ba??=g.locateFile?Aa("wasmInterface.wasm")?"wasmInterface.wasm":g.locateFile?g.locateFile("wasmInterface.wasm",l):l+"wasmInterface.wasm":(new URL("wasmInterface.wasm",import.meta.url)).href;Fa(b,function(c){a(c.instance)}).catch(ba);return{}}(),Ab=a=>(Ab=Z.vh)(a),y=a=>(y=Z.wh)(a),G=a=>(G=Z.xh)(a),Lf=(a,b)=>(Lf=Z.zh)(a,b),Qf=(a,b)=>(Qf=Z.Ah)(a,b),yd=a=>(yd=Z.Bh)(a),vd=a=>(vd=Z.Ch)(a),xd=()=>(xd=Z.Dh)();
g.dynCall_jiji=(a,b,c,d,e)=>(g.dynCall_jiji=Z.Eh)(a,b,c,d,e);g.dynCall_ji=(a,b)=>(g.dynCall_ji=Z.Fh)(a,b);g.dynCall_vij=(a,b,c,d)=>(g.dynCall_vij=Z.Gh)(a,b,c,d);g.dynCall_viijii=(a,b,c,d,e,f,h)=>(g.dynCall_viijii=Z.Hh)(a,b,c,d,e,f,h);g.dynCall_iiiiij=(a,b,c,d,e,f,h)=>(g.dynCall_iiiiij=Z.Ih)(a,b,c,d,e,f,h);g.dynCall_iiiiijj=(a,b,c,d,e,f,h,k,m)=>(g.dynCall_iiiiijj=Z.Jh)(a,b,c,d,e,f,h,k,m);g.dynCall_iiiiiijj=(a,b,c,d,e,f,h,k,m,p)=>(g.dynCall_iiiiiijj=Z.Kh)(a,b,c,d,e,f,h,k,m,p);
function Mf(a,b,c){var d=xd();try{return A(a)(b,c)}catch(e){yd(d);if(e!==e+0)throw e;Qf(1,0)}}function Of(a,b,c,d,e){var f=xd();try{return A(a)(b,c,d,e)}catch(h){yd(f);if(h!==h+0)throw h;Qf(1,0)}}function Nf(a,b,c,d){var e=xd();try{return A(a)(b,c,d)}catch(f){yd(e);if(f!==f+0)throw f;Qf(1,0)}}var Rf;ya=function Sf(){Rf||Tf();Rf||(ya=Sf)};
function Tf(){function a(){if(!Rf&&(Rf=!0,g.calledRun=!0,!la)){Ia(ta);aa(g);g.onRuntimeInitialized?.();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();ua.unshift(b)}Ia(ua)}}if(!(0<wa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)va();Ia(sa);0<wa||(g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);a()},1)):a())}}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Tf();moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default Module;
